/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef TRANSMISSION_H
#define TRANSMISSION_H

/* function declarations */
void init_transmission(void);
FindVarMethod var_transmission;

#endif /* TRANSMISSION_H */
