cmd_modutils/rmmod.o := /opt/lemonix/cdt/bin/arm-linux-gcc -Wp,-MD,modutils/.rmmod.o.d   -std=gnu99 -Iinclude -Ilibbb  -I/home/WORK/eddy-25-Open-EF8M/filesystem_2.5.1.1/src/busybox-1.5.0/libbb -include include/autoconf.h -D_GNU_SOURCE -DNDEBUG  -D"BB_VER=KBUILD_STR(1.5.0)" -DBB_BT=AUTOCONF_TIMESTAMP  -Wall -Wshadow -Wwrite-strings -Wundef -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-declarations -Os -fno-builtin-strlen -finline-limit=0 -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-guess-branch-probability -funsigned-char -static-libgcc -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -Wdeclaration-after-statement -Wno-pointer-sign    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(rmmod)"  -D"KBUILD_MODNAME=KBUILD_STR(rmmod)" -c -o modutils/rmmod.o modutils/rmmod.c

deps_modutils/rmmod.o := \
  modutils/rmmod.c \
    $(wildcard include/config/feature/2/6/modules.h) \
    $(wildcard include/config/feature/2/4/modules.h) \
    $(wildcard include/config/feature/query/module/interface.h) \
  include/busybox.h \
  include/libbb.h \
    $(wildcard include/config/selinux.h) \
    $(wildcard include/config/locale/support.h) \
    $(wildcard include/config/feature/shadowpasswds.h) \
    $(wildcard include/config/lfs.h) \
    $(wildcard include/config/feature/buffers/go/on/stack.h) \
    $(wildcard include/config/buffer.h) \
    $(wildcard include/config/ubuffer.h) \
    $(wildcard include/config/feature/buffers/go/in/bss.h) \
    $(wildcard include/config/feature/ipv6.h) \
    $(wildcard include/config/getopt/long.h) \
    $(wildcard include/config/route.h) \
    $(wildcard include/config/gunzip.h) \
    $(wildcard include/config/ktop.h) \
    $(wildcard include/config/feature/exec/prefer/applets.h) \
    $(wildcard include/config/busybox/exec/path.h) \
    $(wildcard include/config/feature/editing.h) \
    $(wildcard include/config/feature/editing/history.h) \
    $(wildcard include/config/ture/editing/savehistory.h) \
    $(wildcard include/config/feature/editing/savehistory.h) \
    $(wildcard include/config/feature/tab/completion.h) \
    $(wildcard include/config/feature/username/completion.h) \
    $(wildcard include/config/feature/editing/vi.h) \
    $(wildcard include/config/inux.h) \
    $(wildcard include/config/feature/devfs.h) \
  include/platform.h \
    $(wildcard include/config///.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/byteswap.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/byteswap.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/endian.h \
    $(wildcard include/config/.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/features.h \
    $(wildcard include/config/c99.h) \
    $(wildcard include/config/ix.h) \
    $(wildcard include/config/ix2.h) \
    $(wildcard include/config/ix199309.h) \
    $(wildcard include/config/ix199506.h) \
    $(wildcard include/config/en.h) \
    $(wildcard include/config/en/extended.h) \
    $(wildcard include/config/x98.h) \
    $(wildcard include/config/en2k.h) \
    $(wildcard include/config/gefile.h) \
    $(wildcard include/config/gefile64.h) \
    $(wildcard include/config/e/offset64.h) \
    $(wildcard include/config/d.h) \
    $(wildcard include/config/c.h) \
    $(wildcard include/config/ile.h) \
    $(wildcard include/config/ntrant.h) \
    $(wildcard include/config/tify/level.h) \
    $(wildcard include/config/i.h) \
    $(wildcard include/config/ern/inlines.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/cdefs.h \
    $(wildcard include/config/espaces.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/wordsize.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/gnu/stubs.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/endian.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/arpa/inet.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/netinet/in.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/stdint.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/wchar.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/socket.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/uio.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/types.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/types.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/include/stddef.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/typesizes.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/time.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/select.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/select.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/sigset.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/time.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/sysmacros.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/pthreadtypes.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/uio.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/socket.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/include/limits.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/sockaddr.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm/socket.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm/sockios.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/in.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/include/stdbool.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/mount.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/ioctl.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/ioctls.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm/ioctls.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm/ioctl.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/ioctl-types.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/ttydefaults.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/ctype.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/xlocale.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/dirent.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/dirent.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/posix1_lim.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/local_lim.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/linux/limits.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/errno.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/errno.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/linux/errno.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm/errno.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm-generic/errno.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm-generic/errno-base.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/fcntl.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/fcntl.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/stat.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/stat.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/inttypes.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/netdb.h \
    $(wildcard include/config/3/ascii/rules.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/rpc/netdb.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/siginfo.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/netdb.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/setjmp.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/setjmp.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/signal.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/signum.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/sigaction.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/sigcontext.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm/sigcontext.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/sigstack.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/ucontext.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/procfs.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/time.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/user.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/sigthread.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/stdio.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/libio.h \
    $(wildcard include/config/a.h) \
    $(wildcard include/config/ar/t.h) \
    $(wildcard include/config//io/file.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/_G_config.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/wchar.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/gconv.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/include/stdarg.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/stdio_lim.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/sys_errlist.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/stdlib.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/waitflags.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/waitstatus.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/alloca.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/string.h \
    $(wildcard include/config/ing/inlines.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/strings.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/mman.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/mman.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/statfs.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/statfs.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/wait.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/resource.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/resource.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/termios.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/termios.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/unistd.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/posix_opt.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/environments.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/confname.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/getopt.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/utime.h \
  include/pwd_.h \
    $(wildcard include/config/use/bb/pwd/grp.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/pwd.h \
  include/grp_.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/grp.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/param.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/linux/param.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm/param.h \
  include/xatonum.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/sys/syscall.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm/unistd.h \
    $(wildcard include/config//oabi/syscalls.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/linux/linkage.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/linux/config.h \
    $(wildcard include/config/h.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/linux/autoconf.h \
    $(wildcard include/config/arm.h) \
    $(wildcard include/config/mmu.h) \
    $(wildcard include/config/uid16.h) \
    $(wildcard include/config/rwsem/generic/spinlock.h) \
    $(wildcard include/config/generic/calibrate/delay.h) \
    $(wildcard include/config/arch/may/have/pc/fdc.h) \
    $(wildcard include/config/fiq.h) \
    $(wildcard include/config/experimental.h) \
    $(wildcard include/config/clean/compile.h) \
    $(wildcard include/config/broken/on/smp.h) \
    $(wildcard include/config/init/env/arg/limit.h) \
    $(wildcard include/config/localversion.h) \
    $(wildcard include/config/localversion/auto.h) \
    $(wildcard include/config/swap.h) \
    $(wildcard include/config/sysvipc.h) \
    $(wildcard include/config/posix/mqueue.h) \
    $(wildcard include/config/bsd/process/acct.h) \
    $(wildcard include/config/bsd/process/acct/v3.h) \
    $(wildcard include/config/sysctl.h) \
    $(wildcard include/config/audit.h) \
    $(wildcard include/config/hotplug.h) \
    $(wildcard include/config/kobject/uevent.h) \
    $(wildcard include/config/ikconfig.h) \
    $(wildcard include/config/initramfs/source.h) \
    $(wildcard include/config/embedded.h) \
    $(wildcard include/config/kallsyms.h) \
    $(wildcard include/config/kallsyms/all.h) \
    $(wildcard include/config/kallsyms/extra/pass.h) \
    $(wildcard include/config/printk.h) \
    $(wildcard include/config/bug.h) \
    $(wildcard include/config/kmalloc/accounting.h) \
    $(wildcard include/config/audit/bootmem.h) \
    $(wildcard include/config/panic.h) \
    $(wildcard include/config/full/panic.h) \
    $(wildcard include/config/elf/core.h) \
    $(wildcard include/config/base/full.h) \
    $(wildcard include/config/net/small.h) \
    $(wildcard include/config/futex.h) \
    $(wildcard include/config/epoll.h) \
    $(wildcard include/config/aio.h) \
    $(wildcard include/config/xattr.h) \
    $(wildcard include/config/file/locking.h) \
    $(wildcard include/config/ethtool.h) \
    $(wildcard include/config/inetpeer.h) \
    $(wildcard include/config/net/sk/filter.h) \
    $(wildcard include/config/net/dev/multicast.h) \
    $(wildcard include/config/igmp.h) \
    $(wildcard include/config/measure/inlines.h) \
    $(wildcard include/config/cc/optimize/for/size.h) \
    $(wildcard include/config/shmem.h) \
    $(wildcard include/config/cc/align/functions.h) \
    $(wildcard include/config/cc/align/labels.h) \
    $(wildcard include/config/cc/align/loops.h) \
    $(wildcard include/config/cc/align/jumps.h) \
    $(wildcard include/config/tiny/cflags.h) \
    $(wildcard include/config/crc32/tables.h) \
    $(wildcard include/config/slab.h) \
    $(wildcard include/config/mempool.h) \
    $(wildcard include/config/console/translations.h) \
    $(wildcard include/config/binfmt/script.h) \
    $(wildcard include/config/binfmt/elf/aout.h) \
    $(wildcard include/config/max/swapfiles/shift.h) \
    $(wildcard include/config/nr/ldiscs.h) \
    $(wildcard include/config/max/user/rt/prio.h) \
    $(wildcard include/config/ide/hwifs.h) \
    $(wildcard include/config/pci/quirks.h) \
    $(wildcard include/config/cpu/sup/intel.h) \
    $(wildcard include/config/cpu/sup/cyrix.h) \
    $(wildcard include/config/cpu/sup/nsc.h) \
    $(wildcard include/config/cpu/sup/amd.h) \
    $(wildcard include/config/cpu/sup/centaur.h) \
    $(wildcard include/config/cpu/sup/transmeta.h) \
    $(wildcard include/config/cpu/sup/rise.h) \
    $(wildcard include/config/cpu/sup/nexgen.h) \
    $(wildcard include/config/cpu/sup/umc.h) \
    $(wildcard include/config/crc32/calc.h) \
    $(wildcard include/config/tiny/shmem.h) \
    $(wildcard include/config/base/small.h) \
    $(wildcard include/config/slob.h) \
    $(wildcard include/config/modules.h) \
    $(wildcard include/config/module/unload.h) \
    $(wildcard include/config/module/force/unload.h) \
    $(wildcard include/config/obsolete/modparm.h) \
    $(wildcard include/config/modversions.h) \
    $(wildcard include/config/module/srcversion/all.h) \
    $(wildcard include/config/kmod.h) \
    $(wildcard include/config/arch/clps7500.h) \
    $(wildcard include/config/arch/clps711x.h) \
    $(wildcard include/config/arch/co285.h) \
    $(wildcard include/config/arch/ebsa110.h) \
    $(wildcard include/config/arch/camelot.h) \
    $(wildcard include/config/arch/footbridge.h) \
    $(wildcard include/config/arch/integrator.h) \
    $(wildcard include/config/arch/iop3xx.h) \
    $(wildcard include/config/arch/ixp4xx.h) \
    $(wildcard include/config/arch/ixp2000.h) \
    $(wildcard include/config/arch/l7200.h) \
    $(wildcard include/config/arch/pxa.h) \
    $(wildcard include/config/arch/rpc.h) \
    $(wildcard include/config/arch/sa1100.h) \
    $(wildcard include/config/arch/s3c2410.h) \
    $(wildcard include/config/arch/shark.h) \
    $(wildcard include/config/arch/lh7a40x.h) \
    $(wildcard include/config/arch/omap.h) \
    $(wildcard include/config/arch/versatile.h) \
    $(wildcard include/config/arch/imx.h) \
    $(wildcard include/config/arch/h720x.h) \
    $(wildcard include/config/arch/aaec2000.h) \
    $(wildcard include/config/arch/acorn.h) \
    $(wildcard include/config/cpu/32.h) \
    $(wildcard include/config/cpu/arm610.h) \
    $(wildcard include/config/cpu/arm710.h) \
    $(wildcard include/config/cpu/sa110.h) \
    $(wildcard include/config/timer/acorn.h) \
    $(wildcard include/config/isa/dma/api.h) \
    $(wildcard include/config/pccard.h) \
    $(wildcard include/config/preempt.h) \
    $(wildcard include/config/no/idle/hz.h) \
    $(wildcard include/config/aeabi.h) \
    $(wildcard include/config/arch/discontigmem/enable.h) \
    $(wildcard include/config/select/memory/model.h) \
    $(wildcard include/config/flatmem/manual.h) \
    $(wildcard include/config/discontigmem/manual.h) \
    $(wildcard include/config/sparsemem/manual.h) \
    $(wildcard include/config/flatmem.h) \
    $(wildcard include/config/flat/node/mem/map.h) \
    $(wildcard include/config/sparsemem/static.h) \
    $(wildcard include/config/alignment/trap.h) \
    $(wildcard include/config/zboot/rom/text.h) \
    $(wildcard include/config/zboot/rom/bss.h) \
    $(wildcard include/config/cmdline.h) \
    $(wildcard include/config/xip/kernel.h) \
    $(wildcard include/config/fpe/nwfpe.h) \
    $(wildcard include/config/fpe/fastfpe.h) \
    $(wildcard include/config/binfmt/elf.h) \
    $(wildcard include/config/binfmt/aout.h) \
    $(wildcard include/config/binfmt/misc.h) \
    $(wildcard include/config/arthur.h) \
    $(wildcard include/config/pm.h) \
    $(wildcard include/config/apm.h) \
    $(wildcard include/config/net.h) \
    $(wildcard include/config/packet.h) \
    $(wildcard include/config/packet/mmap.h) \
    $(wildcard include/config/unix.h) \
    $(wildcard include/config/xfrm.h) \
    $(wildcard include/config/xfrm/user.h) \
    $(wildcard include/config/xfrm/migrate.h) \
    $(wildcard include/config/xfrm/debug.h) \
    $(wildcard include/config/net/key/module.h) \
    $(wildcard include/config/net/key/migrate.h) \
    $(wildcard include/config/use/policy/fwd.h) \
    $(wildcard include/config/inet.h) \
    $(wildcard include/config/ip/multicast.h) \
    $(wildcard include/config/ip/advanced/router.h) \
    $(wildcard include/config/ask/ip/fib/hash.h) \
    $(wildcard include/config/ip/fib/trie.h) \
    $(wildcard include/config/ip/fib/hash.h) \
    $(wildcard include/config/ip/multiple/tables.h) \
    $(wildcard include/config/ip/route/fwmark.h) \
    $(wildcard include/config/ip/route/multipath.h) \
    $(wildcard include/config/ip/route/multipath/cached.h) \
    $(wildcard include/config/ip/route/verbose.h) \
    $(wildcard include/config/ip/pnp.h) \
    $(wildcard include/config/net/ipip/module.h) \
    $(wildcard include/config/net/ipgre/module.h) \
    $(wildcard include/config/net/ipgre/broadcast.h) \
    $(wildcard include/config/ip/mroute.h) \
    $(wildcard include/config/ip/pimsm/v1.h) \
    $(wildcard include/config/ip/pimsm/v2.h) \
    $(wildcard include/config/arpd.h) \
    $(wildcard include/config/syn/cookies.h) \
    $(wildcard include/config/inet/ah/module.h) \
    $(wildcard include/config/inet/esp/module.h) \
    $(wildcard include/config/inet/ipcomp/module.h) \
    $(wildcard include/config/inet/tunnel/module.h) \
    $(wildcard include/config/inet/diag.h) \
    $(wildcard include/config/inet/tcp/diag.h) \
    $(wildcard include/config/tcp/cong/advanced.h) \
    $(wildcard include/config/tcp/cong/bic.h) \
    $(wildcard include/config/ip/vs/module.h) \
    $(wildcard include/config/ip/vs/debug.h) \
    $(wildcard include/config/ip/vs/tab/bits.h) \
    $(wildcard include/config/ip/vs/proto/tcp.h) \
    $(wildcard include/config/ip/vs/proto/udp.h) \
    $(wildcard include/config/ip/vs/proto/esp.h) \
    $(wildcard include/config/ip/vs/proto/ah.h) \
    $(wildcard include/config/ip/vs/rr/module.h) \
    $(wildcard include/config/ip/vs/wrr/module.h) \
    $(wildcard include/config/ip/vs/lc/module.h) \
    $(wildcard include/config/ip/vs/wlc/module.h) \
    $(wildcard include/config/ip/vs/lblc/module.h) \
    $(wildcard include/config/ip/vs/lblcr/module.h) \
    $(wildcard include/config/ip/vs/dh/module.h) \
    $(wildcard include/config/ip/vs/sh/module.h) \
    $(wildcard include/config/ip/vs/sed/module.h) \
    $(wildcard include/config/ip/vs/nq/module.h) \
    $(wildcard include/config/ip/vs/ftp/module.h) \
    $(wildcard include/config/ipv6/module.h) \
    $(wildcard include/config/ipv6/privacy.h) \
    $(wildcard include/config/ipv6/privacy/md5.h) \
    $(wildcard include/config/ipv6/router/pref.h) \
    $(wildcard include/config/inet6/ah/module.h) \
    $(wildcard include/config/inet6/esp/module.h) \
    $(wildcard include/config/inet6/ipcomp/module.h) \
    $(wildcard include/config/inet6/tunnel/module.h) \
    $(wildcard include/config/ipv6/tunnel/module.h) \
    $(wildcard include/config/ipv6/advanced/router.h) \
    $(wildcard include/config/ipv6/mip6.h) \
    $(wildcard include/config/ipv6/mroute.h) \
    $(wildcard include/config/ipv6/statistics.h) \
    $(wildcard include/config/netfilter.h) \
    $(wildcard include/config/netfilter/debug.h) \
    $(wildcard include/config/bridge/netfilter.h) \
    $(wildcard include/config/netfilter/netlink.h) \
    $(wildcard include/config/ip/nf/conntrack/module.h) \
    $(wildcard include/config/ip/nf/ct/acct.h) \
    $(wildcard include/config/ip/nf/conntrack/mark.h) \
    $(wildcard include/config/ip/nf/conntrack/events.h) \
    $(wildcard include/config/ip/nf/ct/proto/sctp/module.h) \
    $(wildcard include/config/ip/nf/ftp/module.h) \
    $(wildcard include/config/ip/nf/irc/module.h) \
    $(wildcard include/config/ip/nf/netbios/ns.h) \
    $(wildcard include/config/ip/nf/tftp/module.h) \
    $(wildcard include/config/ip/nf/amanda/module.h) \
    $(wildcard include/config/ip/nf/pptp.h) \
    $(wildcard include/config/ip/nf/queue/module.h) \
    $(wildcard include/config/ip/nf/iptables/module.h) \
    $(wildcard include/config/ip/nf/match/limit/module.h) \
    $(wildcard include/config/ip/nf/match/iprange/module.h) \
    $(wildcard include/config/ip/nf/match/mac/module.h) \
    $(wildcard include/config/ip/nf/match/pkttype/module.h) \
    $(wildcard include/config/ip/nf/match/mark/module.h) \
    $(wildcard include/config/ip/nf/match/multiport/module.h) \
    $(wildcard include/config/ip/nf/match/tos/module.h) \
    $(wildcard include/config/ip/nf/match/recent/module.h) \
    $(wildcard include/config/ip/nf/match/ecn/module.h) \
    $(wildcard include/config/ip/nf/match/dscp/module.h) \
    $(wildcard include/config/ip/nf/match/ah/esp/module.h) \
    $(wildcard include/config/ip/nf/match/length/module.h) \
    $(wildcard include/config/ip/nf/match/ttl/module.h) \
    $(wildcard include/config/ip/nf/match/tcpmss/module.h) \
    $(wildcard include/config/ip/nf/match/helper/module.h) \
    $(wildcard include/config/ip/nf/match/state/module.h) \
    $(wildcard include/config/ip/nf/match/conntrack/module.h) \
    $(wildcard include/config/ip/nf/match/owner/module.h) \
    $(wildcard include/config/ip/nf/match/physdev/module.h) \
    $(wildcard include/config/ip/nf/match/addrtype/module.h) \
    $(wildcard include/config/ip/nf/match/realm/module.h) \
    $(wildcard include/config/ip/nf/match/sctp/module.h) \
    $(wildcard include/config/ip/nf/match/dccp.h) \
    $(wildcard include/config/ip/nf/match/comment/module.h) \
    $(wildcard include/config/ip/nf/match/connbytes.h) \
    $(wildcard include/config/ip/nf/match/hashlimit.h) \
    $(wildcard include/config/ip/nf/match/string.h) \
    $(wildcard include/config/ip/nf/filter/module.h) \
    $(wildcard include/config/ip/nf/target/reject/module.h) \
    $(wildcard include/config/ip/nf/target/log/module.h) \
    $(wildcard include/config/ip/nf/target/ulog/module.h) \
    $(wildcard include/config/ip/nf/target/tcpmss/module.h) \
    $(wildcard include/config/ip/nf/target/nfqueue.h) \
    $(wildcard include/config/ip/nf/nat/module.h) \
    $(wildcard include/config/ip/nf/nat/needed.h) \
    $(wildcard include/config/ip/nf/target/masquerade/module.h) \
    $(wildcard include/config/ip/nf/target/redirect/module.h) \
    $(wildcard include/config/ip/nf/target/netmap/module.h) \
    $(wildcard include/config/ip/nf/target/same/module.h) \
    $(wildcard include/config/ip/nf/nat/snmp/basic/module.h) \
    $(wildcard include/config/ip/nf/nat/irc/module.h) \
    $(wildcard include/config/ip/nf/nat/ftp/module.h) \
    $(wildcard include/config/ip/nf/nat/tftp/module.h) \
    $(wildcard include/config/ip/nf/nat/amanda/module.h) \
    $(wildcard include/config/ip/nf/mangle/module.h) \
    $(wildcard include/config/ip/nf/target/tos/module.h) \
    $(wildcard include/config/ip/nf/target/ecn/module.h) \
    $(wildcard include/config/ip/nf/target/dscp/module.h) \
    $(wildcard include/config/ip/nf/target/mark/module.h) \
    $(wildcard include/config/ip/nf/target/classify/module.h) \
    $(wildcard include/config/ip/nf/target/ttl.h) \
    $(wildcard include/config/ip/nf/raw/module.h) \
    $(wildcard include/config/ip/nf/target/notrack/module.h) \
    $(wildcard include/config/ip/nf/arptables/module.h) \
    $(wildcard include/config/ip/nf/arpfilter/module.h) \
    $(wildcard include/config/ip/nf/arp/mangle/module.h) \
    $(wildcard include/config/ip6/nf/queue.h) \
    $(wildcard include/config/ip6/nf/iptables/module.h) \
    $(wildcard include/config/ip6/nf/match/limit/module.h) \
    $(wildcard include/config/ip6/nf/match/mac/module.h) \
    $(wildcard include/config/ip6/nf/match/rt/module.h) \
    $(wildcard include/config/ip6/nf/match/opts/module.h) \
    $(wildcard include/config/ip6/nf/match/frag/module.h) \
    $(wildcard include/config/ip6/nf/match/hl/module.h) \
    $(wildcard include/config/ip6/nf/match/multiport/module.h) \
    $(wildcard include/config/ip6/nf/match/owner/module.h) \
    $(wildcard include/config/ip6/nf/match/mark/module.h) \
    $(wildcard include/config/ip6/nf/match/ipv6header/module.h) \
    $(wildcard include/config/ip6/nf/match/ahesp/module.h) \
    $(wildcard include/config/ip6/nf/match/length/module.h) \
    $(wildcard include/config/ip6/nf/match/eui64/module.h) \
    $(wildcard include/config/ip6/nf/match/physdev/module.h) \
    $(wildcard include/config/ip6/nf/conntrack.h) \
    $(wildcard include/config/ip6/nf/filter/module.h) \
    $(wildcard include/config/ip6/nf/target/log/module.h) \
    $(wildcard include/config/ip6/nf/target/reject.h) \
    $(wildcard include/config/ip6/nf/target/nfqueue.h) \
    $(wildcard include/config/ip6/nf/mangle/module.h) \
    $(wildcard include/config/ip6/nf/target/mark/module.h) \
    $(wildcard include/config/ip6/nf/target/hl.h) \
    $(wildcard include/config/ip6/nf/raw/module.h) \
    $(wildcard include/config/bridge/nf/ebtables/module.h) \
    $(wildcard include/config/bridge/ebt/broute/module.h) \
    $(wildcard include/config/bridge/ebt/t/filter/module.h) \
    $(wildcard include/config/bridge/ebt/t/nat/module.h) \
    $(wildcard include/config/bridge/ebt/802/3/module.h) \
    $(wildcard include/config/bridge/ebt/among/module.h) \
    $(wildcard include/config/bridge/ebt/arp/module.h) \
    $(wildcard include/config/bridge/ebt/ip/module.h) \
    $(wildcard include/config/bridge/ebt/limit/module.h) \
    $(wildcard include/config/bridge/ebt/mark/module.h) \
    $(wildcard include/config/bridge/ebt/pkttype/module.h) \
    $(wildcard include/config/bridge/ebt/stp/module.h) \
    $(wildcard include/config/bridge/ebt/vlan/module.h) \
    $(wildcard include/config/bridge/ebt/arpreply/module.h) \
    $(wildcard include/config/bridge/ebt/dnat/module.h) \
    $(wildcard include/config/bridge/ebt/mark/t/module.h) \
    $(wildcard include/config/bridge/ebt/redirect/module.h) \
    $(wildcard include/config/bridge/ebt/snat/module.h) \
    $(wildcard include/config/bridge/ebt/log/module.h) \
    $(wildcard include/config/bridge/ebt/ulog.h) \
    $(wildcard include/config/ip/dccp.h) \
    $(wildcard include/config/ip/sctp/module.h) \
    $(wildcard include/config/sctp/dbg/msg.h) \
    $(wildcard include/config/sctp/dbg/objcnt.h) \
    $(wildcard include/config/sctp/hmac/none.h) \
    $(wildcard include/config/sctp/hmac/sha1.h) \
    $(wildcard include/config/sctp/hmac/md5.h) \
    $(wildcard include/config/atm/module.h) \
    $(wildcard include/config/atm/clip/module.h) \
    $(wildcard include/config/atm/clip/no/icmp.h) \
    $(wildcard include/config/atm/lane/module.h) \
    $(wildcard include/config/atm/mpoa.h) \
    $(wildcard include/config/atm/br2684/module.h) \
    $(wildcard include/config/atm/br2684/ipfilter.h) \
    $(wildcard include/config/bridge/module.h) \
    $(wildcard include/config/vlan/8021q/module.h) \
    $(wildcard include/config/decnet.h) \
    $(wildcard include/config/llc/module.h) \
    $(wildcard include/config/llc2.h) \
    $(wildcard include/config/ipx/module.h) \
    $(wildcard include/config/ipx/intern.h) \
    $(wildcard include/config/atalk/module.h) \
    $(wildcard include/config/dev/appletalk.h) \
    $(wildcard include/config/ipddp/module.h) \
    $(wildcard include/config/ipddp/encap.h) \
    $(wildcard include/config/ipddp/decap.h) \
    $(wildcard include/config/x25.h) \
    $(wildcard include/config/lapb.h) \
    $(wildcard include/config/net/divert.h) \
    $(wildcard include/config/econet.h) \
    $(wildcard include/config/wan/router/module.h) \
    $(wildcard include/config/net/sched.h) \
    $(wildcard include/config/net/sch/clk/jiffies.h) \
    $(wildcard include/config/net/sch/clk/gettimeofday.h) \
    $(wildcard include/config/net/sch/clk/cpu.h) \
    $(wildcard include/config/net/sch/cbq/module.h) \
    $(wildcard include/config/net/sch/htb/module.h) \
    $(wildcard include/config/net/sch/hfsc/module.h) \
    $(wildcard include/config/net/sch/atm/module.h) \
    $(wildcard include/config/net/sch/prio/module.h) \
    $(wildcard include/config/net/sch/red/module.h) \
    $(wildcard include/config/net/sch/sfq/module.h) \
    $(wildcard include/config/net/sch/teql/module.h) \
    $(wildcard include/config/net/sch/tbf/module.h) \
    $(wildcard include/config/net/sch/gred/module.h) \
    $(wildcard include/config/net/sch/dsmark/module.h) \
    $(wildcard include/config/net/sch/netem/module.h) \
    $(wildcard include/config/net/sch/ingress/module.h) \
    $(wildcard include/config/net/qos.h) \
    $(wildcard include/config/net/estimator.h) \
    $(wildcard include/config/net/cls.h) \
    $(wildcard include/config/net/cls/basic.h) \
    $(wildcard include/config/net/cls/tcindex/module.h) \
    $(wildcard include/config/net/cls/route4/module.h) \
    $(wildcard include/config/net/cls/route.h) \
    $(wildcard include/config/net/cls/fw/module.h) \
    $(wildcard include/config/net/cls/u32/module.h) \
    $(wildcard include/config/cls/u32/perf.h) \
    $(wildcard include/config/net/cls/ind.h) \
    $(wildcard include/config/cls/u32/mark.h) \
    $(wildcard include/config/net/cls/rsvp/module.h) \
    $(wildcard include/config/net/cls/rsvp6/module.h) \
    $(wildcard include/config/net/ematch.h) \
    $(wildcard include/config/net/cls/act.h) \
    $(wildcard include/config/net/cls/police.h) \
    $(wildcard include/config/net/pktgen.h) \
    $(wildcard include/config/hamradio.h) \
    $(wildcard include/config/irda/module.h) \
    $(wildcard include/config/irlan/module.h) \
    $(wildcard include/config/irnet/module.h) \
    $(wildcard include/config/ircomm/module.h) \
    $(wildcard include/config/irda/ultra.h) \
    $(wildcard include/config/irda/cache/last/lsap.h) \
    $(wildcard include/config/irda/fast/rr.h) \
    $(wildcard include/config/irda/debug.h) \
    $(wildcard include/config/irtty/sir/module.h) \
    $(wildcard include/config/dongle.h) \
    $(wildcard include/config/esi/dongle/module.h) \
    $(wildcard include/config/actisys/dongle/module.h) \
    $(wildcard include/config/tekram/dongle/module.h) \
    $(wildcard include/config/litelink/dongle/module.h) \
    $(wildcard include/config/ma600/dongle/module.h) \
    $(wildcard include/config/girbil/dongle/module.h) \
    $(wildcard include/config/mcp2120/dongle/module.h) \
    $(wildcard include/config/old/belkin/dongle/module.h) \
    $(wildcard include/config/act200l/dongle/module.h) \
    $(wildcard include/config/irport/sir.h) \
    $(wildcard include/config/usb/irda/module.h) \
    $(wildcard include/config/sigmatel/fir/module.h) \
    $(wildcard include/config/nsc/fir/module.h) \
    $(wildcard include/config/winbond/fir.h) \
    $(wildcard include/config/smc/ircc/fir.h) \
    $(wildcard include/config/ali/fir.h) \
    $(wildcard include/config/via/fir.h) \
    $(wildcard include/config/bt/module.h) \
    $(wildcard include/config/bt/l2cap/module.h) \
    $(wildcard include/config/bt/sco/module.h) \
    $(wildcard include/config/bt/rfcomm/module.h) \
    $(wildcard include/config/bt/rfcomm/tty.h) \
    $(wildcard include/config/bt/bnep/module.h) \
    $(wildcard include/config/bt/bnep/mc/filter.h) \
    $(wildcard include/config/bt/bnep/proto/filter.h) \
    $(wildcard include/config/bt/cmtp/module.h) \
    $(wildcard include/config/bt/hidp/module.h) \
    $(wildcard include/config/bt/hciusb/module.h) \
    $(wildcard include/config/bt/hciusb/sco.h) \
    $(wildcard include/config/bt/hciuart/module.h) \
    $(wildcard include/config/bt/hciuart/h4.h) \
    $(wildcard include/config/bt/hciuart/bcsp.h) \
    $(wildcard include/config/bt/hciuart/bcsp/txcrc.h) \
    $(wildcard include/config/bt/hcibcm203x/module.h) \
    $(wildcard include/config/bt/hcibpa10x.h) \
    $(wildcard include/config/bt/hcibfusb/module.h) \
    $(wildcard include/config/bt/hcivhci/module.h) \
    $(wildcard include/config/ieee80211.h) \
    $(wildcard include/config/standalone.h) \
    $(wildcard include/config/prevent/firmware/build.h) \
    $(wildcard include/config/fw/loader.h) \
    $(wildcard include/config/debug/driver.h) \
    $(wildcard include/config/mtd/module.h) \
    $(wildcard include/config/mtd/debug.h) \
    $(wildcard include/config/mtd/concat/module.h) \
    $(wildcard include/config/mtd/partitions.h) \
    $(wildcard include/config/mtd/redboot/parts/module.h) \
    $(wildcard include/config/mtd/redboot/directory/block.h) \
    $(wildcard include/config/mtd/redboot/parts/unallocated.h) \
    $(wildcard include/config/mtd/redboot/parts/readonly.h) \
    $(wildcard include/config/mtd/cmdline/parts.h) \
    $(wildcard include/config/mtd/afs/parts.h) \
    $(wildcard include/config/mtd/char/module.h) \
    $(wildcard include/config/mtd/block/module.h) \
    $(wildcard include/config/mtd/block/ro/module.h) \
    $(wildcard include/config/ftl/module.h) \
    $(wildcard include/config/nftl/module.h) \
    $(wildcard include/config/nftl/rw.h) \
    $(wildcard include/config/inftl/module.h) \
    $(wildcard include/config/mtd/cfi/module.h) \
    $(wildcard include/config/mtd/jedecprobe/module.h) \
    $(wildcard include/config/mtd/gen/probe/module.h) \
    $(wildcard include/config/mtd/cfi/adv/options.h) \
    $(wildcard include/config/mtd/map/bank/width/1.h) \
    $(wildcard include/config/mtd/map/bank/width/2.h) \
    $(wildcard include/config/mtd/map/bank/width/4.h) \
    $(wildcard include/config/mtd/map/bank/width/8.h) \
    $(wildcard include/config/mtd/map/bank/width/16.h) \
    $(wildcard include/config/mtd/map/bank/width/32.h) \
    $(wildcard include/config/mtd/cfi/i1.h) \
    $(wildcard include/config/mtd/cfi/i2.h) \
    $(wildcard include/config/mtd/cfi/i4.h) \
    $(wildcard include/config/mtd/cfi/i8.h) \
    $(wildcard include/config/mtd/cfi/intelext/module.h) \
    $(wildcard include/config/mtd/cfi/amdstd/module.h) \
    $(wildcard include/config/mtd/cfi/amdstd/retry.h) \
    $(wildcard include/config/mtd/cfi/staa/module.h) \
    $(wildcard include/config/mtd/cfi/util/module.h) \
    $(wildcard include/config/mtd/ram/module.h) \
    $(wildcard include/config/mtd/rom/module.h) \
    $(wildcard include/config/mtd/absent/module.h) \
    $(wildcard include/config/mtd/xip.h) \
    $(wildcard include/config/mtd/complex/mappings.h) \
    $(wildcard include/config/mtd/physmap.h) \
    $(wildcard include/config/mtd/ppmc280/flash.h) \
    $(wildcard include/config/mtd/multi/physmap.h) \
    $(wildcard include/config/mtd/arm/integrator.h) \
    $(wildcard include/config/mtd/edb7312.h) \
    $(wildcard include/config/mtd/impa7.h) \
    $(wildcard include/config/mtd/platram.h) \
    $(wildcard include/config/mtd/sibley.h) \
    $(wildcard include/config/mtd/slram.h) \
    $(wildcard include/config/mtd/phram.h) \
    $(wildcard include/config/mtd/mtdram/module.h) \
    $(wildcard include/config/mtdram/total/size.h) \
    $(wildcard include/config/mtdram/erase/size.h) \
    $(wildcard include/config/ramtd.h) \
    $(wildcard include/config/mtd/blkmtd.h) \
    $(wildcard include/config/mtd/block2mtd.h) \
    $(wildcard include/config/mtd/doc2000/module.h) \
    $(wildcard include/config/mtd/doc2001.h) \
    $(wildcard include/config/mtd/doc2001plus/module.h) \
    $(wildcard include/config/mtd/docprobe/module.h) \
    $(wildcard include/config/mtd/docecc/module.h) \
    $(wildcard include/config/mtd/docprobe/advanced.h) \
    $(wildcard include/config/mtd/docprobe/address.h) \
    $(wildcard include/config/mtd/nand/module.h) \
    $(wildcard include/config/mtd/nand/verify/write.h) \
    $(wildcard include/config/mtd/nand/ids/module.h) \
    $(wildcard include/config/mtd/nand/diskonchip.h) \
    $(wildcard include/config/mtd/nand/nandsim.h) \
    $(wildcard include/config/parport/module.h) \
    $(wildcard include/config/parport/pc/module.h) \
    $(wildcard include/config/parport/pc/fifo.h) \
    $(wildcard include/config/parport/pc/superio.h) \
    $(wildcard include/config/parport/not/pc.h) \
    $(wildcard include/config/parport/arc.h) \
    $(wildcard include/config/parport/gsc.h) \
    $(wildcard include/config/parport/1284.h) \
    $(wildcard include/config/blk/dev/fd/module.h) \
    $(wildcard include/config/paride.h) \
    $(wildcard include/config/blk/dev/cow/common.h) \
    $(wildcard include/config/blk/dev/loop/module.h) \
    $(wildcard include/config/blk/dev/cryptoloop/module.h) \
    $(wildcard include/config/blk/dev/nbd/module.h) \
    $(wildcard include/config/blk/dev/ub.h) \
    $(wildcard include/config/blk/dev/ram.h) \
    $(wildcard include/config/blk/dev/ram/count.h) \
    $(wildcard include/config/blk/dev/ram/size.h) \
    $(wildcard include/config/blk/dev/initrd.h) \
    $(wildcard include/config/cdrom/pktcdvd.h) \
    $(wildcard include/config/iosched/noop.h) \
    $(wildcard include/config/iosched/as.h) \
    $(wildcard include/config/iosched/deadline.h) \
    $(wildcard include/config/iosched/cfq.h) \
    $(wildcard include/config/ata/over/eth.h) \
    $(wildcard include/config/ide.h) \
    $(wildcard include/config/blk/dev/ide.h) \
    $(wildcard include/config/blk/dev/ide/sata.h) \
    $(wildcard include/config/zylonite/true/ide.h) \
    $(wildcard include/config/blk/dev/idedisk.h) \
    $(wildcard include/config/idedisk/multi/mode.h) \
    $(wildcard include/config/blk/dev/idecd.h) \
    $(wildcard include/config/blk/dev/idetape.h) \
    $(wildcard include/config/blk/dev/idefloppy.h) \
    $(wildcard include/config/blk/dev/idescsi/module.h) \
    $(wildcard include/config/ide/task/ioctl.h) \
    $(wildcard include/config/ide/generic.h) \
    $(wildcard include/config/ide/arm.h) \
    $(wildcard include/config/blk/dev/ide/icside.h) \
    $(wildcard include/config/blk/dev/ide/rapide.h) \
    $(wildcard include/config/blk/dev/idedma.h) \
    $(wildcard include/config/idedma/auto.h) \
    $(wildcard include/config/blk/dev/hd.h) \
    $(wildcard include/config/raid/attrs.h) \
    $(wildcard include/config/scsi/module.h) \
    $(wildcard include/config/scsi/proc/fs.h) \
    $(wildcard include/config/blk/dev/sd/module.h) \
    $(wildcard include/config/chr/dev/st/module.h) \
    $(wildcard include/config/chr/dev/osst/module.h) \
    $(wildcard include/config/blk/dev/sr/module.h) \
    $(wildcard include/config/blk/dev/sr/vendor.h) \
    $(wildcard include/config/chr/dev/sg/module.h) \
    $(wildcard include/config/chr/dev/sch.h) \
    $(wildcard include/config/scsi/multi/lun.h) \
    $(wildcard include/config/scsi/constants.h) \
    $(wildcard include/config/scsi/logging.h) \
    $(wildcard include/config/scsi/spi/attrs/module.h) \
    $(wildcard include/config/scsi/fc/attrs/module.h) \
    $(wildcard include/config/scsi/iscsi/attrs.h) \
    $(wildcard include/config/scsi/sas/attrs.h) \
    $(wildcard include/config/scsi/sata/module.h) \
    $(wildcard include/config/scsi/ppa/module.h) \
    $(wildcard include/config/scsi/imm/module.h) \
    $(wildcard include/config/scsi/izip/epp16.h) \
    $(wildcard include/config/scsi/izip/slow/ctr.h) \
    $(wildcard include/config/scsi/debug.h) \
    $(wildcard include/config/scsi/arxescsi.h) \
    $(wildcard include/config/scsi/cumana/2.h) \
    $(wildcard include/config/scsi/eesoxscsi.h) \
    $(wildcard include/config/scsi/powertecscsi.h) \
    $(wildcard include/config/scsi/cumana/1.h) \
    $(wildcard include/config/scsi/oak1.h) \
    $(wildcard include/config/md.h) \
    $(wildcard include/config/blk/dev/md.h) \
    $(wildcard include/config/md/linear/module.h) \
    $(wildcard include/config/md/raid0/module.h) \
    $(wildcard include/config/md/raid1/module.h) \
    $(wildcard include/config/md/raid10/module.h) \
    $(wildcard include/config/md/raid5/module.h) \
    $(wildcard include/config/md/raid6/module.h) \
    $(wildcard include/config/md/multipath/module.h) \
    $(wildcard include/config/md/faulty.h) \
    $(wildcard include/config/blk/dev/dm/module.h) \
    $(wildcard include/config/dm/crypt/module.h) \
    $(wildcard include/config/dm/snapshot/module.h) \
    $(wildcard include/config/dm/mirror/module.h) \
    $(wildcard include/config/dm/zero/module.h) \
    $(wildcard include/config/dm/multipath.h) \
    $(wildcard include/config/fusion.h) \
    $(wildcard include/config/netdevices.h) \
    $(wildcard include/config/dummy/module.h) \
    $(wildcard include/config/bonding/module.h) \
    $(wildcard include/config/equalizer/module.h) \
    $(wildcard include/config/tun/module.h) \
    $(wildcard include/config/phylib.h) \
    $(wildcard include/config/net/ethernet.h) \
    $(wildcard include/config/mii/module.h) \
    $(wildcard include/config/arm/ether1.h) \
    $(wildcard include/config/arm/ether3.h) \
    $(wildcard include/config/arm/etherh.h) \
    $(wildcard include/config/smc91x.h) \
    $(wildcard include/config/dm9000.h) \
    $(wildcard include/config/net/pocket.h) \
    $(wildcard include/config/de600/module.h) \
    $(wildcard include/config/de620/module.h) \
    $(wildcard include/config/net/radio.h) \
    $(wildcard include/config/strip.h) \
    $(wildcard include/config/atmel/module.h) \
    $(wildcard include/config/hostap.h) \
    $(wildcard include/config/wan.h) \
    $(wildcard include/config/atm/tcp/module.h) \
    $(wildcard include/config/plip/module.h) \
    $(wildcard include/config/ppp/module.h) \
    $(wildcard include/config/ppp/multilink.h) \
    $(wildcard include/config/ppp/filter.h) \
    $(wildcard include/config/ppp/async/module.h) \
    $(wildcard include/config/ppp/sync/tty/module.h) \
    $(wildcard include/config/ppp/deflate/module.h) \
    $(wildcard include/config/ppp/bsdcomp.h) \
    $(wildcard include/config/pppoe/module.h) \
    $(wildcard include/config/pppoatm/module.h) \
    $(wildcard include/config/slip.h) \
    $(wildcard include/config/shaper.h) \
    $(wildcard include/config/netconsole/module.h) \
    $(wildcard include/config/netpoll.h) \
    $(wildcard include/config/netpoll/rx.h) \
    $(wildcard include/config/netpoll/trap.h) \
    $(wildcard include/config/net/poll/controller.h) \
    $(wildcard include/config/isdn/module.h) \
    $(wildcard include/config/isdn/i4l/module.h) \
    $(wildcard include/config/isdn/ppp.h) \
    $(wildcard include/config/isdn/ppp/vj.h) \
    $(wildcard include/config/isdn/mpp.h) \
    $(wildcard include/config/ippp/filter.h) \
    $(wildcard include/config/isdn/ppp/bsdcomp.h) \
    $(wildcard include/config/isdn/audio.h) \
    $(wildcard include/config/isdn/tty/fax.h) \
    $(wildcard include/config/isdn/drv/loop.h) \
    $(wildcard include/config/isdn/diversion.h) \
    $(wildcard include/config/isdn/drv/hisax/module.h) \
    $(wildcard include/config/hisax/euro.h) \
    $(wildcard include/config/de/aoc.h) \
    $(wildcard include/config/hisax/no/sendcomplete.h) \
    $(wildcard include/config/hisax/no/llc.h) \
    $(wildcard include/config/hisax/no/keypad.h) \
    $(wildcard include/config/hisax/1tr6.h) \
    $(wildcard include/config/hisax/ni1.h) \
    $(wildcard include/config/hisax/max/cards.h) \
    $(wildcard include/config/hisax/16/3.h) \
    $(wildcard include/config/hisax/s0box.h) \
    $(wildcard include/config/hisax/fritzpci.h) \
    $(wildcard include/config/hisax/avm/a1/pcmcia.h) \
    $(wildcard include/config/hisax/elsa.h) \
    $(wildcard include/config/hisax/diehldiva.h) \
    $(wildcard include/config/hisax/sedlbauer.h) \
    $(wildcard include/config/hisax/niccy.h) \
    $(wildcard include/config/hisax/gazel.h) \
    $(wildcard include/config/hisax/hfc/sx.h) \
    $(wildcard include/config/hisax/debug.h) \
    $(wildcard include/config/hisax/st5481/module.h) \
    $(wildcard include/config/hisax/hfcusb/module.h) \
    $(wildcard include/config/hisax/hfc4s8s.h) \
    $(wildcard include/config/hisax/hdlc.h) \
    $(wildcard include/config/isdn/capi/module.h) \
    $(wildcard include/config/isdn/drv/avmb1/verbose/reason.h) \
    $(wildcard include/config/isdn/capi/middleware.h) \
    $(wildcard include/config/isdn/capi/capi20/module.h) \
    $(wildcard include/config/isdn/capi/capifs/bool.h) \
    $(wildcard include/config/isdn/capi/capifs/module.h) \
    $(wildcard include/config/isdn/capi/capidrv/module.h) \
    $(wildcard include/config/capi/avm.h) \
    $(wildcard include/config/isdn/drv/avmb1/b1pcmcia.h) \
    $(wildcard include/config/capi/eicon.h) \
    $(wildcard include/config/input.h) \
    $(wildcard include/config/input/mousedev.h) \
    $(wildcard include/config/input/mousedev/psaux.h) \
    $(wildcard include/config/input/mousedev/screen/x.h) \
    $(wildcard include/config/input/mousedev/screen/y.h) \
    $(wildcard include/config/input/joydev/module.h) \
    $(wildcard include/config/input/tsdev.h) \
    $(wildcard include/config/input/tslibdev.h) \
    $(wildcard include/config/input/evdev.h) \
    $(wildcard include/config/input/evbug.h) \
    $(wildcard include/config/input/keyboard.h) \
    $(wildcard include/config/keyboard/atkbd.h) \
    $(wildcard include/config/keyboard/sunkbd.h) \
    $(wildcard include/config/keyboard/lkkbd.h) \
    $(wildcard include/config/keyboard/xtkbd.h) \
    $(wildcard include/config/keyboard/newton.h) \
    $(wildcard include/config/input/mouse.h) \
    $(wildcard include/config/mouse/ps2.h) \
    $(wildcard include/config/mouse/serial/module.h) \
    $(wildcard include/config/ial/module.h) \
    $(wildcard include/config/mouse/riscpc.h) \
    $(wildcard include/config/cpc.h) \
    $(wildcard include/config/mouse/vsxxxaa/module.h) \
    $(wildcard include/config/xxaa/module.h) \
    $(wildcard include/config/input/joystick.h) \
    $(wildcard include/config/joystick/analog/module.h) \
    $(wildcard include/config/joystick/a3d/module.h) \
    $(wildcard include/config/joystick/adi/module.h) \
    $(wildcard include/config/joystick/cobra/module.h) \
    $(wildcard include/config/joystick/gf2k/module.h) \
    $(wildcard include/config/joystick/grip/module.h) \
    $(wildcard include/config/joystick/grip/mp/module.h) \
    $(wildcard include/config/joystick/guillemot/module.h) \
    $(wildcard include/config/joystick/interact/module.h) \
    $(wildcard include/config/joystick/sidewinder/module.h) \
    $(wildcard include/config/joystick/tmdc/module.h) \
    $(wildcard include/config/joystick/iforce/module.h) \
    $(wildcard include/config/joystick/iforce/usb.h) \
    $(wildcard include/config/joystick/iforce/232.h) \
    $(wildcard include/config/joystick/warrior/module.h) \
    $(wildcard include/config/joystick/magellan/module.h) \
    $(wildcard include/config/joystick/spaceorb/module.h) \
    $(wildcard include/config/joystick/spaceball/module.h) \
    $(wildcard include/config/joystick/stinger/module.h) \
    $(wildcard include/config/joystick/twidjoy.h) \
    $(wildcard include/config/joystick/db9/module.h) \
    $(wildcard include/config/joystick/gamecon/module.h) \
    $(wildcard include/config/joystick/turbografx/module.h) \
    $(wildcard include/config/joystick/joydump/module.h) \
    $(wildcard include/config/input/touchscreen.h) \
    $(wildcard include/config/touchscreen/gunze/module.h) \
    $(wildcard include/config/touchscreen/elo.h) \
    $(wildcard include/config/touchscreen/mtouch.h) \
    $(wildcard include/config/touchscreen/mk712.h) \
    $(wildcard include/config/input/misc.h) \
    $(wildcard include/config/input/uinput/module.h) \
    $(wildcard include/config/serio.h) \
    $(wildcard include/config/serio/serport.h) \
    $(wildcard include/config/serio/parkbd.h) \
    $(wildcard include/config/serio/rpckbd.h) \
    $(wildcard include/config/serio/libps2.h) \
    $(wildcard include/config/serio/raw.h) \
    $(wildcard include/config/gameport/module.h) \
    $(wildcard include/config/gameport/ns558/module.h) \
    $(wildcard include/config/gameport/l4/module.h) \
    $(wildcard include/config/vt.h) \
    $(wildcard include/config/vt/console.h) \
    $(wildcard include/config/hw/console.h) \
    $(wildcard include/config/serial/nonstandard.h) \
    $(wildcard include/config/computone.h) \
    $(wildcard include/config/rocketport/module.h) \
    $(wildcard include/config/cyclades.h) \
    $(wildcard include/config/digiepca.h) \
    $(wildcard include/config/moxa/intellio.h) \
    $(wildcard include/config/moxa/smartio.h) \
    $(wildcard include/config/isi.h) \
    $(wildcard include/config/synclinkmp/module.h) \
    $(wildcard include/config/n/hdlc/module.h) \
    $(wildcard include/config/riscom8.h) \
    $(wildcard include/config/specialix.h) \
    $(wildcard include/config/sx.h) \
    $(wildcard include/config/rio.h) \
    $(wildcard include/config/staldrv.h) \
    $(wildcard include/config/stallion.h) \
    $(wildcard include/config/istallion.h) \
    $(wildcard include/config/serial/8250.h) \
    $(wildcard include/config/serial/8250/console.h) \
    $(wildcard include/config/serial/8250/nr/uarts.h) \
    $(wildcard include/config/serial/8250/extended.h) \
    $(wildcard include/config/serial/8250/many/ports.h) \
    $(wildcard include/config/serial/8250/share/irq.h) \
    $(wildcard include/config/serial/8250/detect/irq.h) \
    $(wildcard include/config/serial/8250/rsa.h) \
    $(wildcard include/config/serial/8250/acorn.h) \
    $(wildcard include/config/serial/core.h) \
    $(wildcard include/config/serial/core/console.h) \
    $(wildcard include/config/unix98/ptys.h) \
    $(wildcard include/config/legacy/ptys.h) \
    $(wildcard include/config/printer/module.h) \
    $(wildcard include/config/lp/console.h) \
    $(wildcard include/config/ppdev/module.h) \
    $(wildcard include/config/tipar/module.h) \
    $(wildcard include/config/ipmi/handler/module.h) \
    $(wildcard include/config/ipmi/panic/event.h) \
    $(wildcard include/config/ipmi/device/interface/module.h) \
    $(wildcard include/config/ipmi/si/module.h) \
    $(wildcard include/config/ipmi/watchdog/module.h) \
    $(wildcard include/config/ipmi/poweroff/module.h) \
    $(wildcard include/config/watchdog.h) \
    $(wildcard include/config/watchdog/nowayout.h) \
    $(wildcard include/config/soft/watchdog/module.h) \
    $(wildcard include/config/usbpcwatchdog/module.h) \
    $(wildcard include/config/nvram/module.h) \
    $(wildcard include/config/rtc.h) \
    $(wildcard include/config/dtlk/module.h) \
    $(wildcard include/config/r3964/module.h) \
    $(wildcard include/config/raw/driver.h) \
    $(wildcard include/config/i2c/module.h) \
    $(wildcard include/config/i2c/chardev/module.h) \
    $(wildcard include/config/i2c/algobit/module.h) \
    $(wildcard include/config/i2c/algopcf/module.h) \
    $(wildcard include/config/i2c/algopca/module.h) \
    $(wildcard include/config/i2c/isa/module.h) \
    $(wildcard include/config/i2c/parport.h) \
    $(wildcard include/config/i2c/parport/light.h) \
    $(wildcard include/config/i2c/stub.h) \
    $(wildcard include/config/i2c/pca/isa/module.h) \
    $(wildcard include/config/sensors/ds1337.h) \
    $(wildcard include/config/sensors/ds1374.h) \
    $(wildcard include/config/sensors/eeprom/module.h) \
    $(wildcard include/config/sensors/pcf8574/module.h) \
    $(wildcard include/config/sensors/pca9539.h) \
    $(wildcard include/config/sensors/pcf8591/module.h) \
    $(wildcard include/config/sensors/rtc8564/module.h) \
    $(wildcard include/config/sensors/max6875.h) \
    $(wildcard include/config/i2c/debug/core.h) \
    $(wildcard include/config/i2c/debug/algo.h) \
    $(wildcard include/config/i2c/debug/bus.h) \
    $(wildcard include/config/i2c/debug/chip.h) \
    $(wildcard include/config/hwmon.h) \
    $(wildcard include/config/hwmon/vid/module.h) \
    $(wildcard include/config/sensors/adm1021/module.h) \
    $(wildcard include/config/sensors/adm1025/module.h) \
    $(wildcard include/config/sensors/adm1026.h) \
    $(wildcard include/config/sensors/adm1031/module.h) \
    $(wildcard include/config/sensors/adm9240.h) \
    $(wildcard include/config/sensors/asb100/module.h) \
    $(wildcard include/config/sensors/atxp1.h) \
    $(wildcard include/config/sensors/ds1621/module.h) \
    $(wildcard include/config/sensors/fscher/module.h) \
    $(wildcard include/config/sensors/fscpos.h) \
    $(wildcard include/config/sensors/gl518sm/module.h) \
    $(wildcard include/config/sensors/gl520sm.h) \
    $(wildcard include/config/sensors/it87/module.h) \
    $(wildcard include/config/sensors/lm63.h) \
    $(wildcard include/config/sensors/lm75/module.h) \
    $(wildcard include/config/sensors/lm77/module.h) \
    $(wildcard include/config/sensors/lm78/module.h) \
    $(wildcard include/config/sensors/lm80/module.h) \
    $(wildcard include/config/sensors/lm83/module.h) \
    $(wildcard include/config/sensors/lm85/module.h) \
    $(wildcard include/config/sensors/lm87.h) \
    $(wildcard include/config/sensors/lm90/module.h) \
    $(wildcard include/config/sensors/lm92.h) \
    $(wildcard include/config/sensors/max1619/module.h) \
    $(wildcard include/config/sensors/pc87360.h) \
    $(wildcard include/config/sensors/smsc47m1/module.h) \
    $(wildcard include/config/sensors/smsc47b397.h) \
    $(wildcard include/config/sensors/w83781d/module.h) \
    $(wildcard include/config/sensors/w83792d.h) \
    $(wildcard include/config/sensors/w83l785ts/module.h) \
    $(wildcard include/config/sensors/w83627hf/module.h) \
    $(wildcard include/config/sensors/w83627ehf.h) \
    $(wildcard include/config/hwmon/debug/chip.h) \
    $(wildcard include/config/w1.h) \
    $(wildcard include/config/video/dev/module.h) \
    $(wildcard include/config/video/bwqcam/module.h) \
    $(wildcard include/config/video/cqcam/module.h) \
    $(wildcard include/config/video/w9966/module.h) \
    $(wildcard include/config/video/cpia/module.h) \
    $(wildcard include/config/video/cpia/pp/module.h) \
    $(wildcard include/config/video/cpia/usb/module.h) \
    $(wildcard include/config/video/saa5246a/module.h) \
    $(wildcard include/config/video/saa5249/module.h) \
    $(wildcard include/config/tuner/3036/module.h) \
    $(wildcard include/config/video/ovcamchip/module.h) \
    $(wildcard include/config/pxa/camera/ms.h) \
    $(wildcard include/config/pxa/camera/zl.h) \
    $(wildcard include/config/radio/maestro/module.h) \
    $(wildcard include/config/dvb.h) \
    $(wildcard include/config/dvb/core/module.h) \
    $(wildcard include/config/dvb/usb.h) \
    $(wildcard include/config/dvb/ttusb/budget/module.h) \
    $(wildcard include/config/dvb/ttusb/dec/module.h) \
    $(wildcard include/config/dvb/cinergyt2.h) \
    $(wildcard include/config/dvb/b2c2/flexcop.h) \
    $(wildcard include/config/dvb/stv0299/module.h) \
    $(wildcard include/config/dvb/cx24110/module.h) \
    $(wildcard include/config/dvb/tda8083/module.h) \
    $(wildcard include/config/dvb/tda80xx.h) \
    $(wildcard include/config/dvb/mt312/module.h) \
    $(wildcard include/config/dvb/ves1x93/module.h) \
    $(wildcard include/config/dvb/s5h1420.h) \
    $(wildcard include/config/dvb/sp8870.h) \
    $(wildcard include/config/dvb/sp887x.h) \
    $(wildcard include/config/dvb/cx22700/module.h) \
    $(wildcard include/config/dvb/cx22702.h) \
    $(wildcard include/config/dvb/l64781.h) \
    $(wildcard include/config/dvb/tda1004x/module.h) \
    $(wildcard include/config/dvb/nxt6000/module.h) \
    $(wildcard include/config/dvb/mt352.h) \
    $(wildcard include/config/dvb/dib3000mb.h) \
    $(wildcard include/config/dvb/dib3000mc.h) \
    $(wildcard include/config/dvb/atmel/at76c651/module.h) \
    $(wildcard include/config/dvb/ves1820/module.h) \
    $(wildcard include/config/dvb/tda10021.h) \
    $(wildcard include/config/dvb/stv0297.h) \
    $(wildcard include/config/dvb/nxt2002.h) \
    $(wildcard include/config/dvb/or51211.h) \
    $(wildcard include/config/dvb/or51132.h) \
    $(wildcard include/config/dvb/bcm3510.h) \
    $(wildcard include/config/dvb/lgdt330x.h) \
    $(wildcard include/config/fb.h) \
    $(wildcard include/config/fb/cfb/fillrect.h) \
    $(wildcard include/config/fb/cfb/copyarea.h) \
    $(wildcard include/config/fb/cfb/imageblit.h) \
    $(wildcard include/config/fb/soft/cursor.h) \
    $(wildcard include/config/fb/macmodes.h) \
    $(wildcard include/config/fb/mode/helpers.h) \
    $(wildcard include/config/fb/tileblitting.h) \
    $(wildcard include/config/fb/acorn.h) \
    $(wildcard include/config/fb/s1d13xxx.h) \
    $(wildcard include/config/fb/virtual.h) \
    $(wildcard include/config/dummy/console.h) \
    $(wildcard include/config/framebuffer/console.h) \
    $(wildcard include/config/fonts.h) \
    $(wildcard include/config/font/8x8.h) \
    $(wildcard include/config/font/8x16.h) \
    $(wildcard include/config/font/acorn/8x8.h) \
    $(wildcard include/config/logo.h) \
    $(wildcard include/config/logo/linux/mono.h) \
    $(wildcard include/config/logo/linux/vga16.h) \
    $(wildcard include/config/logo/linux/clut224.h) \
    $(wildcard include/config/backlight/lcd/support.h) \
    $(wildcard include/config/sound/module.h) \
    $(wildcard include/config/snd/module.h) \
    $(wildcard include/config/snd/timer/module.h) \
    $(wildcard include/config/snd/pcm/module.h) \
    $(wildcard include/config/snd/hwdep/module.h) \
    $(wildcard include/config/snd/rawmidi/module.h) \
    $(wildcard include/config/snd/sequencer/module.h) \
    $(wildcard include/config/snd/seq/dummy/module.h) \
    $(wildcard include/config/snd/ossemul.h) \
    $(wildcard include/config/snd/mixer/oss/module.h) \
    $(wildcard include/config/snd/pcm/oss/module.h) \
    $(wildcard include/config/snd/sequencer/oss.h) \
    $(wildcard include/config/snd/rtctimer/module.h) \
    $(wildcard include/config/snd/seq/rtctimer/default.h) \
    $(wildcard include/config/snd/verbose/printk.h) \
    $(wildcard include/config/snd/debug.h) \
    $(wildcard include/config/snd/generic/driver.h) \
    $(wildcard include/config/snd/mpu401/uart/module.h) \
    $(wildcard include/config/snd/dummy/module.h) \
    $(wildcard include/config/snd/virmidi/module.h) \
    $(wildcard include/config/snd/mtpav/module.h) \
    $(wildcard include/config/snd/serial/u16550.h) \
    $(wildcard include/config/snd/mpu401/module.h) \
    $(wildcard include/config/snd/usb/audio/module.h) \
    $(wildcard include/config/sound/prime.h) \
    $(wildcard include/config/usb/arch/has/hcd.h) \
    $(wildcard include/config/usb/arch/has/ohci.h) \
    $(wildcard include/config/usb.h) \
    $(wildcard include/config/usb/debug.h) \
    $(wildcard include/config/usb/devicefs.h) \
    $(wildcard include/config/usb/bandwidth.h) \
    $(wildcard include/config/usb/dynamic/minors.h) \
    $(wildcard include/config/usb/suspend.h) \
    $(wildcard include/config/usb/otg.h) \
    $(wildcard include/config/usb/isp116x/hcd.h) \
    $(wildcard include/config/usb/sl811/hcd.h) \
    $(wildcard include/config/obsolete/oss/usb/driver.h) \
    $(wildcard include/config/usb/acm/module.h) \
    $(wildcard include/config/usb/printer/module.h) \
    $(wildcard include/config/usb/storage/module.h) \
    $(wildcard include/config/usb/storage/debug.h) \
    $(wildcard include/config/usb/storage/datafab.h) \
    $(wildcard include/config/usb/storage/freecom.h) \
    $(wildcard include/config/usb/storage/isd200.h) \
    $(wildcard include/config/usb/storage/dpcm.h) \
    $(wildcard include/config/usb/storage/usbat.h) \
    $(wildcard include/config/usb/storage/sddr09.h) \
    $(wildcard include/config/usb/storage/sddr55.h) \
    $(wildcard include/config/usb/storage/jumpshot.h) \
    $(wildcard include/config/usb/storage/onetouch.h) \
    $(wildcard include/config/usb/hid.h) \
    $(wildcard include/config/usb/hidinput.h) \
    $(wildcard include/config/hid/ff.h) \
    $(wildcard include/config/hid/pid.h) \
    $(wildcard include/config/logitech/ff.h) \
    $(wildcard include/config/thrustmaster/ff.h) \
    $(wildcard include/config/usb/hiddev.h) \
    $(wildcard include/config/usb/aiptek/module.h) \
    $(wildcard include/config/usb/wacom/module.h) \
    $(wildcard include/config/usb/acecad.h) \
    $(wildcard include/config/usb/kbtab/module.h) \
    $(wildcard include/config/usb/powermate/module.h) \
    $(wildcard include/config/usb/mtouch/module.h) \
    $(wildcard include/config/usb/itmtouch.h) \
    $(wildcard include/config/usb/egalax/module.h) \
    $(wildcard include/config/usb/yealink.h) \
    $(wildcard include/config/usb/xpad/module.h) \
    $(wildcard include/config/usb/ati/remote/module.h) \
    $(wildcard include/config/usb/keyspan/remote.h) \
    $(wildcard include/config/usb/appletouch.h) \
    $(wildcard include/config/usb/mdc800/module.h) \
    $(wildcard include/config/usb/microtek/module.h) \
    $(wildcard include/config/usb/dabusb/module.h) \
    $(wildcard include/config/usb/vicam/module.h) \
    $(wildcard include/config/usb/dsbr/module.h) \
    $(wildcard include/config/usb/ibmcam/module.h) \
    $(wildcard include/config/usb/konicawc/module.h) \
    $(wildcard include/config/usb/ov511/module.h) \
    $(wildcard include/config/usb/se401/module.h) \
    $(wildcard include/config/usb/sn9c102/module.h) \
    $(wildcard include/config/usb/stv680/module.h) \
    $(wildcard include/config/usb/w9968cf/module.h) \
    $(wildcard include/config/usb/pwc.h) \
    $(wildcard include/config/usb/catc/module.h) \
    $(wildcard include/config/usb/kaweth/module.h) \
    $(wildcard include/config/usb/pegasus/module.h) \
    $(wildcard include/config/usb/rtl8150/module.h) \
    $(wildcard include/config/usb/usbnet/module.h) \
    $(wildcard include/config/usb/net/ax8817x/module.h) \
    $(wildcard include/config/usb/net/cdcether/module.h) \
    $(wildcard include/config/usb/net/gl620a.h) \
    $(wildcard include/config/usb/net/net1080/module.h) \
    $(wildcard include/config/usb/net/plusb.h) \
    $(wildcard include/config/usb/net/rndis/host.h) \
    $(wildcard include/config/usb/net/cdc/subset.h) \
    $(wildcard include/config/usb/net/zaurus/module.h) \
    $(wildcard include/config/usb/zd1201.h) \
    $(wildcard include/config/usb/mon.h) \
    $(wildcard include/config/usb/uss720/module.h) \
    $(wildcard include/config/usb/serial/module.h) \
    $(wildcard include/config/usb/serial/generic.h) \
    $(wildcard include/config/usb/serial/airprime.h) \
    $(wildcard include/config/usb/serial/belkin/module.h) \
    $(wildcard include/config/usb/serial/whiteheat.h) \
    $(wildcard include/config/usb/serial/digi/acceleport/module.h) \
    $(wildcard include/config/usb/serial/cp2101.h) \
    $(wildcard include/config/usb/serial/cypress/m8.h) \
    $(wildcard include/config/usb/serial/empeg/module.h) \
    $(wildcard include/config/usb/serial/ftdi/sio/module.h) \
    $(wildcard include/config/usb/serial/visor/module.h) \
    $(wildcard include/config/usb/serial/ipaq/module.h) \
    $(wildcard include/config/usb/serial/ir/module.h) \
    $(wildcard include/config/usb/serial/edgeport/module.h) \
    $(wildcard include/config/usb/serial/edgeport/ti/module.h) \
    $(wildcard include/config/usb/serial/garmin.h) \
    $(wildcard include/config/usb/serial/ipw.h) \
    $(wildcard include/config/usb/serial/keyspan/pda/module.h) \
    $(wildcard include/config/usb/serial/keyspan/module.h) \
    $(wildcard include/config/usb/serial/keyspan/mpr.h) \
    $(wildcard include/config/usb/serial/keyspan/usa28.h) \
    $(wildcard include/config/usb/serial/keyspan/usa28x.h) \
    $(wildcard include/config/usb/serial/keyspan/usa28xa.h) \
    $(wildcard include/config/usb/serial/keyspan/usa28xb.h) \
    $(wildcard include/config/usb/serial/keyspan/usa19.h) \
    $(wildcard include/config/usb/serial/keyspan/usa18x.h) \
    $(wildcard include/config/usb/serial/keyspan/usa19w.h) \
    $(wildcard include/config/usb/serial/keyspan/usa19qw.h) \
    $(wildcard include/config/usb/serial/keyspan/usa19qi.h) \
    $(wildcard include/config/usb/serial/keyspan/usa49w.h) \
    $(wildcard include/config/usb/serial/keyspan/usa49wlc.h) \
    $(wildcard include/config/usb/serial/klsi/module.h) \
    $(wildcard include/config/usb/serial/kobil/sct/module.h) \
    $(wildcard include/config/usb/serial/mct/u232/module.h) \
    $(wildcard include/config/usb/serial/pl2303/module.h) \
    $(wildcard include/config/usb/serial/hp4x.h) \
    $(wildcard include/config/usb/serial/safe/module.h) \
    $(wildcard include/config/usb/serial/safe/padded.h) \
    $(wildcard include/config/usb/serial/ti.h) \
    $(wildcard include/config/usb/serial/cyberjack/module.h) \
    $(wildcard include/config/usb/serial/xircom/module.h) \
    $(wildcard include/config/usb/serial/omninet/module.h) \
    $(wildcard include/config/usb/ezusb.h) \
    $(wildcard include/config/usb/emi62/module.h) \
    $(wildcard include/config/usb/emi26.h) \
    $(wildcard include/config/usb/auerswald/module.h) \
    $(wildcard include/config/usb/rio500/module.h) \
    $(wildcard include/config/usb/legotower/module.h) \
    $(wildcard include/config/usb/lcd/module.h) \
    $(wildcard include/config/usb/led/module.h) \
    $(wildcard include/config/usb/cytherm.h) \
    $(wildcard include/config/usb/phidgetkit.h) \
    $(wildcard include/config/usb/phidgetservo/module.h) \
    $(wildcard include/config/usb/idmouse.h) \
    $(wildcard include/config/usb/ld.h) \
    $(wildcard include/config/usb/test/module.h) \
    $(wildcard include/config/usb/atm/module.h) \
    $(wildcard include/config/usb/speedtouch/module.h) \
    $(wildcard include/config/usb/cxacru.h) \
    $(wildcard include/config/usb/xusbatm.h) \
    $(wildcard include/config/usb/gadget.h) \
    $(wildcard include/config/mmc.h) \
    $(wildcard include/config/mmc/debug.h) \
    $(wildcard include/config/mmc/block.h) \
    $(wildcard include/config/mmc/protocol.h) \
    $(wildcard include/config/ext2/fs.h) \
    $(wildcard include/config/ext2/fs/xattr.h) \
    $(wildcard include/config/ext2/fs/posix/acl.h) \
    $(wildcard include/config/ext2/fs/security.h) \
    $(wildcard include/config/ext2/fs/xip.h) \
    $(wildcard include/config/ext3/fs/module.h) \
    $(wildcard include/config/ext3/fs/xattr.h) \
    $(wildcard include/config/ext3/fs/posix/acl.h) \
    $(wildcard include/config/ext3/fs/security.h) \
    $(wildcard include/config/jbd/module.h) \
    $(wildcard include/config/jbd/debug.h) \
    $(wildcard include/config/fs/mbcache.h) \
    $(wildcard include/config/reiserfs/fs/module.h) \
    $(wildcard include/config/reiserfs/check.h) \
    $(wildcard include/config/reiserfs/proc/info.h) \
    $(wildcard include/config/reiserfs/fs/xattr.h) \
    $(wildcard include/config/reiserfs/fs/posix/acl.h) \
    $(wildcard include/config/reiserfs/fs/security.h) \
    $(wildcard include/config/jfs/fs/module.h) \
    $(wildcard include/config/jfs/posix/acl.h) \
    $(wildcard include/config/jfs/security.h) \
    $(wildcard include/config/jfs/debug.h) \
    $(wildcard include/config/jfs/statistics.h) \
    $(wildcard include/config/fs/posix/acl.h) \
    $(wildcard include/config/xfs/fs/module.h) \
    $(wildcard include/config/xfs/export.h) \
    $(wildcard include/config/xfs/quota.h) \
    $(wildcard include/config/xfs/security.h) \
    $(wildcard include/config/xfs/posix/acl.h) \
    $(wildcard include/config/xfs/rt.h) \
    $(wildcard include/config/minix/fs/module.h) \
    $(wildcard include/config/romfs/fs/module.h) \
    $(wildcard include/config/inotify.h) \
    $(wildcard include/config/quota.h) \
    $(wildcard include/config/qfmt/v1.h) \
    $(wildcard include/config/qfmt/v2.h) \
    $(wildcard include/config/quotactl.h) \
    $(wildcard include/config/dnotify.h) \
    $(wildcard include/config/autofs/fs/module.h) \
    $(wildcard include/config/autofs4/fs/module.h) \
    $(wildcard include/config/fuse/fs.h) \
    $(wildcard include/config/iso9660/fs.h) \
    $(wildcard include/config/joliet.h) \
    $(wildcard include/config/zisofs.h) \
    $(wildcard include/config/zisofs/fs.h) \
    $(wildcard include/config/udf/fs/module.h) \
    $(wildcard include/config/udf/nls.h) \
    $(wildcard include/config/fat/fs/module.h) \
    $(wildcard include/config/msdos/fs/module.h) \
    $(wildcard include/config/vfat/fs/module.h) \
    $(wildcard include/config/fat/default/codepage.h) \
    $(wildcard include/config/fat/default/iocharset.h) \
    $(wildcard include/config/ntfs/fs.h) \
    $(wildcard include/config/proc/fs.h) \
    $(wildcard include/config/sysfs.h) \
    $(wildcard include/config/tmpfs.h) \
    $(wildcard include/config/hugetlb/page.h) \
    $(wildcard include/config/ramfs.h) \
    $(wildcard include/config/relayfs/fs.h) \
    $(wildcard include/config/adfs/fs.h) \
    $(wildcard include/config/affs/fs/module.h) \
    $(wildcard include/config/hfs/fs/module.h) \
    $(wildcard include/config/hfsplus/fs/module.h) \
    $(wildcard include/config/befs/fs/module.h) \
    $(wildcard include/config/befs/debug.h) \
    $(wildcard include/config/bfs/fs/module.h) \
    $(wildcard include/config/efs/fs/module.h) \
    $(wildcard include/config/yaffs/fs.h) \
    $(wildcard include/config/jffs/fs.h) \
    $(wildcard include/config/jffs2/fs/module.h) \
    $(wildcard include/config/jffs2/fs/debug.h) \
    $(wildcard include/config/jffs2/fs/writebuffer.h) \
    $(wildcard include/config/jffs2/forced/buffer/flush.h) \
    $(wildcard include/config/jffs2/compression/options.h) \
    $(wildcard include/config/jffs2/zlib.h) \
    $(wildcard include/config/jffs2/rtime.h) \
    $(wildcard include/config/jffs2/rubin.h) \
    $(wildcard include/config/cramfs/module.h) \
    $(wildcard include/config/squashfs.h) \
    $(wildcard include/config/cramfs/linear.h) \
    $(wildcard include/config/vxfs/fs/module.h) \
    $(wildcard include/config/hpfs/fs.h) \
    $(wildcard include/config/qnx4fs/fs/module.h) \
    $(wildcard include/config/sysv/fs/module.h) \
    $(wildcard include/config/ufs/fs/module.h) \
    $(wildcard include/config/ufs/fs/write.h) \
    $(wildcard include/config/union/fs.h) \
    $(wildcard include/config/nfs/fs/module.h) \
    $(wildcard include/config/nfs/v3.h) \
    $(wildcard include/config/nfs/v3/acl.h) \
    $(wildcard include/config/nfs/v4.h) \
    $(wildcard include/config/nfs/directio.h) \
    $(wildcard include/config/nfsd/module.h) \
    $(wildcard include/config/nfsd/v3.h) \
    $(wildcard include/config/nfsd/v3/acl.h) \
    $(wildcard include/config/nfsd/v4.h) \
    $(wildcard include/config/nfsd/tcp.h) \
    $(wildcard include/config/lockd/module.h) \
    $(wildcard include/config/lockd/v4.h) \
    $(wildcard include/config/exportfs/module.h) \
    $(wildcard include/config/nfs/common.h) \
    $(wildcard include/config/sunrpc/module.h) \
    $(wildcard include/config/sunrpc/gss/module.h) \
    $(wildcard include/config/rpcsec/gss/krb5/module.h) \
    $(wildcard include/config/rpcsec/gss/spkm3/module.h) \
    $(wildcard include/config/smb/fs/module.h) \
    $(wildcard include/config/smb/nls/default.h) \
    $(wildcard include/config/cifs/module.h) \
    $(wildcard include/config/cifs/stats.h) \
    $(wildcard include/config/cifs/xattr.h) \
    $(wildcard include/config/cifs/posix.h) \
    $(wildcard include/config/cifs/experimental.h) \
    $(wildcard include/config/ncp/fs/module.h) \
    $(wildcard include/config/ncpfs/packet/signing.h) \
    $(wildcard include/config/ncpfs/ioctl/locking.h) \
    $(wildcard include/config/ncpfs/strong.h) \
    $(wildcard include/config/ncpfs/nfs/ns.h) \
    $(wildcard include/config/ncpfs/os2/ns.h) \
    $(wildcard include/config/ncpfs/smalldos.h) \
    $(wildcard include/config/ncpfs/nls.h) \
    $(wildcard include/config/ncpfs/extras.h) \
    $(wildcard include/config/coda/fs.h) \
    $(wildcard include/config/afs/fs.h) \
    $(wildcard include/config/9p/fs.h) \
    $(wildcard include/config/partition/advanced.h) \
    $(wildcard include/config/acorn/partition.h) \
    $(wildcard include/config/acorn/partition/cumana.h) \
    $(wildcard include/config/acorn/partition/eesox.h) \
    $(wildcard include/config/acorn/partition/ics.h) \
    $(wildcard include/config/acorn/partition/adfs.h) \
    $(wildcard include/config/acorn/partition/powertec.h) \
    $(wildcard include/config/acorn/partition/riscix.h) \
    $(wildcard include/config/osf/partition.h) \
    $(wildcard include/config/amiga/partition.h) \
    $(wildcard include/config/atari/partition.h) \
    $(wildcard include/config/mac/partition.h) \
    $(wildcard include/config/msdos/partition.h) \
    $(wildcard include/config/bsd/disklabel.h) \
    $(wildcard include/config/minix/subpartition.h) \
    $(wildcard include/config/solaris/x86/partition.h) \
    $(wildcard include/config/unixware/disklabel.h) \
    $(wildcard include/config/ldm/partition.h) \
    $(wildcard include/config/sgi/partition.h) \
    $(wildcard include/config/ultrix/partition.h) \
    $(wildcard include/config/sun/partition.h) \
    $(wildcard include/config/efi/partition.h) \
    $(wildcard include/config/nls.h) \
    $(wildcard include/config/nls/default.h) \
    $(wildcard include/config/nls/codepage/437.h) \
    $(wildcard include/config/nls/codepage/737/module.h) \
    $(wildcard include/config/nls/codepage/775/module.h) \
    $(wildcard include/config/nls/codepage/850/module.h) \
    $(wildcard include/config/nls/codepage/852/module.h) \
    $(wildcard include/config/nls/codepage/855/module.h) \
    $(wildcard include/config/nls/codepage/857/module.h) \
    $(wildcard include/config/nls/codepage/860/module.h) \
    $(wildcard include/config/nls/codepage/861/module.h) \
    $(wildcard include/config/nls/codepage/862/module.h) \
    $(wildcard include/config/nls/codepage/863/module.h) \
    $(wildcard include/config/nls/codepage/864/module.h) \
    $(wildcard include/config/nls/codepage/865/module.h) \
    $(wildcard include/config/nls/codepage/866/module.h) \
    $(wildcard include/config/nls/codepage/869/module.h) \
    $(wildcard include/config/nls/codepage/936/module.h) \
    $(wildcard include/config/nls/codepage/950/module.h) \
    $(wildcard include/config/nls/codepage/932/module.h) \
    $(wildcard include/config/nls/codepage/949/module.h) \
    $(wildcard include/config/nls/codepage/874/module.h) \
    $(wildcard include/config/nls/iso8859/8/module.h) \
    $(wildcard include/config/nls/codepage/1250/module.h) \
    $(wildcard include/config/nls/codepage/1251/module.h) \
    $(wildcard include/config/nls/ascii.h) \
    $(wildcard include/config/nls/iso8859/1/module.h) \
    $(wildcard include/config/nls/iso8859/2/module.h) \
    $(wildcard include/config/nls/iso8859/3/module.h) \
    $(wildcard include/config/nls/iso8859/4/module.h) \
    $(wildcard include/config/nls/iso8859/5/module.h) \
    $(wildcard include/config/nls/iso8859/6/module.h) \
    $(wildcard include/config/nls/iso8859/7/module.h) \
    $(wildcard include/config/nls/iso8859/9/module.h) \
    $(wildcard include/config/nls/iso8859/13/module.h) \
    $(wildcard include/config/nls/iso8859/14/module.h) \
    $(wildcard include/config/nls/iso8859/15/module.h) \
    $(wildcard include/config/nls/koi8/r/module.h) \
    $(wildcard include/config/nls/koi8/u/module.h) \
    $(wildcard include/config/nls/utf8/module.h) \
    $(wildcard include/config/profiling.h) \
    $(wildcard include/config/oprofile/module.h) \
    $(wildcard include/config/ltt.h) \
    $(wildcard include/config/printk/time.h) \
    $(wildcard include/config/debug/kernel.h) \
    $(wildcard include/config/magic/sysrq.h) \
    $(wildcard include/config/log/buf/shift.h) \
    $(wildcard include/config/detect/softlockup.h) \
    $(wildcard include/config/schedstats.h) \
    $(wildcard include/config/debug/slab.h) \
    $(wildcard include/config/debug/spinlock.h) \
    $(wildcard include/config/debug/spinlock/sleep.h) \
    $(wildcard include/config/debug/kobject.h) \
    $(wildcard include/config/debug/bugverbose.h) \
    $(wildcard include/config/debug/info.h) \
    $(wildcard include/config/debug/fs.h) \
    $(wildcard include/config/frame/pointer.h) \
    $(wildcard include/config/want/extra/debug/information.h) \
    $(wildcard include/config/kgdb.h) \
    $(wildcard include/config/debug/user.h) \
    $(wildcard include/config/debug/waitq.h) \
    $(wildcard include/config/debug/errors.h) \
    $(wildcard include/config/debug/ll.h) \
    $(wildcard include/config/kft.h) \
    $(wildcard include/config/keys.h) \
    $(wildcard include/config/security.h) \
    $(wildcard include/config/security/network.h) \
    $(wildcard include/config/security/capabilities.h) \
    $(wildcard include/config/security/rootplug.h) \
    $(wildcard include/config/security/seclvl.h) \
    $(wildcard include/config/security/selinux.h) \
    $(wildcard include/config/security/selinux/bootparam.h) \
    $(wildcard include/config/security/selinux/bootparam/value.h) \
    $(wildcard include/config/security/selinux/disable.h) \
    $(wildcard include/config/security/selinux/develop.h) \
    $(wildcard include/config/security/selinux/avc/stats.h) \
    $(wildcard include/config/security/selinux/checkreqprot/value.h) \
    $(wildcard include/config/crypto.h) \
    $(wildcard include/config/crypto/hmac.h) \
    $(wildcard include/config/crypto/xcbc.h) \
    $(wildcard include/config/crypto/null/module.h) \
    $(wildcard include/config/crypto/md4/module.h) \
    $(wildcard include/config/crypto/md5.h) \
    $(wildcard include/config/crypto/sha1.h) \
    $(wildcard include/config/crypto/sha256/module.h) \
    $(wildcard include/config/crypto/sha512/module.h) \
    $(wildcard include/config/crypto/wp512/module.h) \
    $(wildcard include/config/crypto/tgr192.h) \
    $(wildcard include/config/crypto/des/module.h) \
    $(wildcard include/config/crypto/blowfish/module.h) \
    $(wildcard include/config/crypto/twofish/module.h) \
    $(wildcard include/config/crypto/serpent/module.h) \
    $(wildcard include/config/crypto/aes.h) \
    $(wildcard include/config/crypto/cast5/module.h) \
    $(wildcard include/config/crypto/cast6/module.h) \
    $(wildcard include/config/crypto/tea/module.h) \
    $(wildcard include/config/crypto/arc4/module.h) \
    $(wildcard include/config/crypto/khazad/module.h) \
    $(wildcard include/config/crypto/anubis.h) \
    $(wildcard include/config/crypto/deflate/module.h) \
    $(wildcard include/config/crypto/michael/mic/module.h) \
    $(wildcard include/config/crypto/crc32c/module.h) \
    $(wildcard include/config/crypto/test.h) \
    $(wildcard include/config/crc/ccitt/module.h) \
    $(wildcard include/config/crc16.h) \
    $(wildcard include/config/crc32.h) \
    $(wildcard include/config/libcrc32c/module.h) \
    $(wildcard include/config/zlib/inflate.h) \
    $(wildcard include/config/zlib/deflate/module.h) \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/asm/linkage.h \
  /opt/lemonix/cdt/bin/../lib/gcc/arm-linux-gnueabi/4.1.1/../../../../arm-linux-gnueabi/include/bits/syscall.h \

modutils/rmmod.o: $(deps_modutils/rmmod.o)

$(deps_modutils/rmmod.o):
