/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate_access.conf 15179 2006-09-08 15:44:37Z dts12 $
 */
#ifndef SYSBAS_H
#define SYSBAS_H

/** other required module components */
//config_require(sysbas_access)
//config_require(sysbas_checkfns)

/* function declarations */
void init_sysbas(void);

/* table handlers */
void initialize_table_serialTable(void);
Netsnmp_Node_Handler serialTable_handler;

void initialize_table_gpioTable(void);
Netsnmp_Node_Handler gpioTable_handler;

/* scalar handlers */
Netsnmp_Node_Handler handle_macAddress;
Netsnmp_Node_Handler handle_ipAddress;
Netsnmp_Node_Handler handle_subnetMask;
Netsnmp_Node_Handler handle_gatewayAddress;
Netsnmp_Node_Handler handle_dnsServerAddress;
Netsnmp_Node_Handler handle_ddnsServerAddress;
Netsnmp_Node_Handler handle_ntpServerAddress;
Netsnmp_Node_Handler handle_portViewAddress;
Netsnmp_Node_Handler handle_lineType;
Netsnmp_Node_Handler handle_deviceName;
Netsnmp_Node_Handler handle_username;
Netsnmp_Node_Handler handle_password;
Netsnmp_Node_Handler handle_portViewPortNumber;
Netsnmp_Node_Handler handle_snmpAgentEnable;
Netsnmp_Node_Handler handle_telnetServerEnable;
Netsnmp_Node_Handler handle_ftpServerEnable;
Netsnmp_Node_Handler handle_webServerEnable;
Netsnmp_Node_Handler handle_sshServerEnable;
Netsnmp_Node_Handler handle_targetAgentEnable;
Netsnmp_Node_Handler handle_modelName;
Netsnmp_Node_Handler handle_ddnsUsername;
Netsnmp_Node_Handler handle_ddnsPassword;
Netsnmp_Node_Handler handle_website;
Netsnmp_Node_Handler handle_contact;
// mcpanic 8508
Netsnmp_Node_Handler handle_v1ReadWrite;
Netsnmp_Node_Handler handle_v3ReadWrite;
Netsnmp_Node_Handler handle_v3Username;
Netsnmp_Node_Handler handle_v3Password;

Netsnmp_Node_Handler handle_kernelVersion;
Netsnmp_Node_Handler handle_filesystemVersion;
Netsnmp_Node_Handler handle_bootloaderVersion;
Netsnmp_Node_Handler handle_reboot;
Netsnmp_Node_Handler handle_trapIPAddress;
Netsnmp_Node_Handler handle_trapPortNumber;
Netsnmp_Node_Handler handle_trapOption;

/* Trap handlers */
int send_systemRestartNotification_trap(void);
int send_portConnectionNotification_trap(void);


/* column number definitions for table serialTable */
#include "sysbas_columns.h"

/* enum definions */
#include "sysbas_enums.h"


/* column number definitions for table gpioTable */
#include "sysbas_columns.h"

/* enum definions */
#include "sysbas_enums.h"

#endif /** SYSBAS_H */
