/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.6 2003/02/20 00:52:07 hardaker Exp $
 */

/***********************************************************************
 *   This file is auto-generated and SHOULD NOT BE EDITED by hand.
 *   Modify the sysbas_checkfns_local.[ch] files insead.
 *   (so that you can regenerate this one as mib2c improvements are made)
 ***********************************************************************/
#ifndef SYSBAS_CHECKFNS_H
#define SYSBAS_CHECKFNS_H

/** make sure we load the functions that you can modify */
//config_require(sysbas_checkfns_local)

/* these functions are designed to check incoming values for 
columns in the serialTable table for legality with respect to 
datatype and value.
 */

      int check_portName(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
      int check_serialRowStatus(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
      int check_resetPort(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for 
columns in the gpioTable table for legality with respect to 
datatype and value.
 */

      int check_gpioSocketNumber(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
      int check_gpioMode(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
      int check_gpioValue(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
      int check_gpioRowStatus(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);

#endif /* SYSBAS_CHECKFNS_H */

