/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_enums.conf 12909 2005-09-29 22:16:22Z hardaker $
 */
#ifndef SYSBAS_ENUMS_H
#define SYSBAS_ENUMS_H

/* enums for column protocol */
           #define PROTOCOL_DISABLED		0
           #define PROTOCOL_COMREDIRECT		1
           #define PROTOCOL_TCPSERVER		2
           #define PROTOCOL_TCPCLIENT		3
           #define PROTOCOL_TCPBROADCAST		4
           #define PROTOCOL_TCPMULTIPLEX		5
           #define PROTOCOL_UDPSERVER		6
           #define PROTOCOL_UDPCLIENT		7

/* enums for column deviceType */
           #define DEVICETYPE_DATA		0
           #define DEVICETYPE_MODEM		1

/* enums for column bypassEnable */
           #define BYPASSENABLE_TRUE		1
           #define BYPASSENABLE_FALSE		2

/* enums for column loginEnable */
           #define LOGINENABLE_TRUE		1
           #define LOGINENABLE_FALSE		2

/* enums for column connectionStatus */
           #define CONNECTIONSTATUS_IDLE		0
           #define CONNECTIONSTATUS_CONNECTED		1

/* enums for column serialRowStatus */
           #define SERIALROWSTATUS_ACTIVE		1
           #define SERIALROWSTATUS_NOTINSERVICE		2
           #define SERIALROWSTATUS_NOTREADY		3
           #define SERIALROWSTATUS_CREATEANDGO		4
           #define SERIALROWSTATUS_CREATEANDWAIT		5
           #define SERIALROWSTATUS_DESTROY		6

/* enums for column gpioMode */
           #define GPIOMODE_INPUT		0
           #define GPIOMODE_OUTPUT		1

/* enums for column gpioRowStatus */
           #define GPIOROWSTATUS_ACTIVE		1
           #define GPIOROWSTATUS_NOTINSERVICE		2
           #define GPIOROWSTATUS_NOTREADY		3
           #define GPIOROWSTATUS_CREATEANDGO		4
           #define GPIOROWSTATUS_CREATEANDWAIT		5
           #define GPIOROWSTATUS_DESTROY		6


/* enums for scalar lineType */
#define LINETYPE_STATICIP		1
#define LINETYPE_DHCP		2

/* enums for scalar snmpAgentEnable */
#define SNMPAGENTENABLE_FALSE		0
#define SNMPAGENTENABLE_TRUE		1

/* enums for scalar telnetServerEnable */
#define TELNETSERVERENABLE_FALSE		0
#define TELNETSERVERENABLE_TRUE		1

/* enums for scalar ftpServerEnable */
#define FTPSERVERENABLE_FALSE		0
#define FTPSERVERENABLE_TRUE		1

/* enums for scalar webServerEnable */
#define WEBSERVERENABLE_FALSE		0
#define WEBSERVERENABLE_TRUE		1

/* enums for scalar sshServerEnable */
#define SSHSERVERENABLE_FALSE		0
#define SSHSERVERENABLE_TRUE		1

/* enums for scalar targetAgentEnable */
#define TARGETAGENTENABLE_FALSE		0
#define TARGETAGENTENABLE_TRUE		1

/* enums for scalar trapOption */
#define TRAPOPTION_NONE		0
#define TRAPOPTION_SYSTEMRESTARTNOTIFICATIONENABLED		1
#define TRAPOPTION_PORTCONNECTIONNOTIFICATIONENABLED		2
#define TRAPOPTION_ALLNOTIFICATIONSENABLED		3

#endif /* SYSBAS_ENUMS_H */
