/*
 * Note: this file originally auto-generated by mib2c using
 *        : : mib2c.check_values_local.conf 10232 2004-05-04 23:35:32Z hardaker $
 * 
 */
#ifndef SYSBAS_CHECKFNS_H
#define SYSBAS_CHECKFNS_H

/* these functions are designed to check incoming values for 
columns in the serialTable table for legality with respect to 
datatype and value according to local conventions.  You should modify
them as appropriate.  They will be called from parent check_value
functions that are auto-generated using mib2c and the parent functions
should NOT be modified.
 */

    int check_portName_local(int type, char *val, size_t val_len, char *old_val, size_t old_val_len);
    int check_serialRowStatus_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_resetPort_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for 
columns in the gpioTable table for legality with respect to 
datatype and value according to local conventions.  You should modify
them as appropriate.  They will be called from parent check_value
functions that are auto-generated using mib2c and the parent functions
should NOT be modified.
 */

    int check_gpioSocketNumber_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_gpioMode_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_gpioValue_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_gpioRowStatus_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);

#endif /* SYSBAS_CHECKFNS_H */

