/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf 7011 2002-05-08 05:42:47Z hardaker $
 */
#ifndef SYSBAS_COLUMNS_H
#define SYSBAS_COLUMNS_H

/* column number definitions for table serialTable */
       #define COLUMN_PORTINDEX		1
       #define COLUMN_PORTNAME		2
       #define COLUMN_SOCKETNUMBER		3
       #define COLUMN_PROTOCOL		4
       #define COLUMN_DEVICETYPE		5
       #define COLUMN_REMOTEIPADDRESS		6
       #define COLUMN_REMOTESOCKETNUMBER		7
       #define COLUMN_BYPASSENABLE		8
       #define COLUMN_LOGINENABLE		9
       #define COLUMN_LOGINUSERNAME		10
       #define COLUMN_LOGINPASSWORD		11
       #define COLUMN_CONNECTIONCOUNT		12
       #define COLUMN_CONNECTIONSTATUS		13
       #define COLUMN_SERIALROWSTATUS		14
       #define COLUMN_RESETPORT		15
       #define COLUMN_KEEPALIVE		16

/* column number definitions for table gpioTable */
       #define COLUMN_GPIOINDEXNUMBER		1
       #define COLUMN_GPIOSOCKETNUMBER		2
       #define COLUMN_GPIOMODE		3
       #define COLUMN_GPIOVALUE		4
       #define COLUMN_GPIOROWSTATUS		5
#endif /* SYSBAS_COLUMNS_H */
