/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_enums.conf 12909 2005-09-29 22:16:22Z hardaker $
 */
#ifndef MIB-2_ENUMS_H
#define MIB-2_ENUMS_H

/* enums for column ifType */
           #define IFTYPE_OTHER		1
           #define IFTYPE_REGULAR1822		2
           #define IFTYPE_HDH1822		3
           #define IFTYPE_DDNX25		4
           #define IFTYPE_RFC877X25		5
           #define IFTYPE_ETHERNETCSMACD		6
           #define IFTYPE_ISO88023CSMACD		7
           #define IFTYPE_ISO88024TOKENBUS		8
           #define IFTYPE_ISO88025TOKENRING		9
           #define IFTYPE_ISO88026MAN		10
           #define IFTYPE_STARLAN		11
           #define IFTYPE_PROTEON10MBIT		12
           #define IFTYPE_PROTEON80MBIT		13
           #define IFTYPE_HYPERCHANNEL		14
           #define IFTYPE_FDDI		15
           #define IFTYPE_LAPB		16
           #define IFTYPE_SDLC		17
           #define IFTYPE_DS1		18
           #define IFTYPE_E1		19
           #define IFTYPE_BASICISDN		20
           #define IFTYPE_PRIMARYISDN		21
           #define IFTYPE_PROPPOINTTOPOINTSERIAL		22
           #define IFTYPE_PPP		23
           #define IFTYPE_SOFTWARELOOPBACK		24
           #define IFTYPE_EON		25
           #define IFTYPE_ETHERNET3MBIT		26
           #define IFTYPE_NSIP		27
           #define IFTYPE_SLIP		28
           #define IFTYPE_ULTRA		29
           #define IFTYPE_DS3		30
           #define IFTYPE_SIP		31
           #define IFTYPE_FRAMERELAY		32
           #define IFTYPE_RS232		33
           #define IFTYPE_PARA		34
           #define IFTYPE_ARCNET		35
           #define IFTYPE_ARCNETPLUS		36
           #define IFTYPE_ATM		37
           #define IFTYPE_MIOX25		38
           #define IFTYPE_SONET		39
           #define IFTYPE_X25PLE		40
           #define IFTYPE_ISO88022LLC		41
           #define IFTYPE_LOCALTALK		42
           #define IFTYPE_SMDSDXI		43
           #define IFTYPE_FRAMERELAYSERVICE		44
           #define IFTYPE_V35		45
           #define IFTYPE_HSSI		46
           #define IFTYPE_HIPPI		47
           #define IFTYPE_MODEM		48
           #define IFTYPE_AAL5		49
           #define IFTYPE_SONETPATH		50
           #define IFTYPE_SONETVT		51
           #define IFTYPE_SMDSICIP		52
           #define IFTYPE_PROPVIRTUAL		53
           #define IFTYPE_PROPMULTIPLEXOR		54
           #define IFTYPE_IEEE80212		55
           #define IFTYPE_FIBRECHANNEL		56
           #define IFTYPE_HIPPIINTERFACE		57
           #define IFTYPE_FRAMERELAYINTERCONNECT		58
           #define IFTYPE_AFLANE8023		59
           #define IFTYPE_AFLANE8025		60
           #define IFTYPE_CCTEMUL		61
           #define IFTYPE_FASTETHER		62
           #define IFTYPE_ISDN		63
           #define IFTYPE_V11		64
           #define IFTYPE_V36		65
           #define IFTYPE_G703AT64K		66
           #define IFTYPE_G703AT2MB		67
           #define IFTYPE_QLLC		68
           #define IFTYPE_FASTETHERFX		69
           #define IFTYPE_CHANNEL		70
           #define IFTYPE_IEEE80211		71
           #define IFTYPE_IBM370PARCHAN		72
           #define IFTYPE_ESCON		73
           #define IFTYPE_DLSW		74
           #define IFTYPE_ISDNS		75
           #define IFTYPE_ISDNU		76
           #define IFTYPE_LAPD		77
           #define IFTYPE_IPSWITCH		78
           #define IFTYPE_RSRB		79
           #define IFTYPE_ATMLOGICAL		80
           #define IFTYPE_DS0		81
           #define IFTYPE_DS0BUNDLE		82
           #define IFTYPE_BSC		83
           #define IFTYPE_ASYNC		84
           #define IFTYPE_CNR		85
           #define IFTYPE_ISO88025DTR		86
           #define IFTYPE_EPLRS		87
           #define IFTYPE_ARAP		88
           #define IFTYPE_PROPCNLS		89
           #define IFTYPE_HOSTPAD		90
           #define IFTYPE_TERMPAD		91
           #define IFTYPE_FRAMERELAYMPI		92
           #define IFTYPE_X213		93
           #define IFTYPE_ADSL		94
           #define IFTYPE_RADSL		95
           #define IFTYPE_SDSL		96
           #define IFTYPE_VDSL		97
           #define IFTYPE_ISO88025CRFPINT		98
           #define IFTYPE_MYRINET		99
           #define IFTYPE_VOICEEM		100
           #define IFTYPE_VOICEFXO		101
           #define IFTYPE_VOICEFXS		102
           #define IFTYPE_VOICEENCAP		103
           #define IFTYPE_VOICEOVERIP		104
           #define IFTYPE_ATMDXI		105
           #define IFTYPE_ATMFUNI		106
           #define IFTYPE_ATMIMA		107
           #define IFTYPE_PPPMULTILINKBUNDLE		108
           #define IFTYPE_IPOVERCDLC		109
           #define IFTYPE_IPOVERCLAW		110
           #define IFTYPE_STACKTOSTACK		111
           #define IFTYPE_VIRTUALIPADDRESS		112
           #define IFTYPE_MPC		113
           #define IFTYPE_IPOVERATM		114
           #define IFTYPE_ISO88025FIBER		115
           #define IFTYPE_TDLC		116
           #define IFTYPE_GIGABITETHERNET		117
           #define IFTYPE_HDLC		118
           #define IFTYPE_LAPF		119
           #define IFTYPE_V37		120
           #define IFTYPE_X25MLP		121
           #define IFTYPE_X25HUNTGROUP		122
           #define IFTYPE_TRASNPHDLC		123
           #define IFTYPE_INTERLEAVE		124
           #define IFTYPE_FAST		125
           #define IFTYPE_IP		126
           #define IFTYPE_DOCSCABLEMACLAYER		127
           #define IFTYPE_DOCSCABLEDOWNSTREAM		128
           #define IFTYPE_DOCSCABLEUPSTREAM		129
           #define IFTYPE_A12MPPSWITCH		130
           #define IFTYPE_TUNNEL		131
           #define IFTYPE_COFFEE		132
           #define IFTYPE_CES		133
           #define IFTYPE_ATMSUBINTERFACE		134
           #define IFTYPE_L2VLAN		135
           #define IFTYPE_L3IPVLAN		136
           #define IFTYPE_L3IPXVLAN		137
           #define IFTYPE_DIGITALPOWERLINE		138
           #define IFTYPE_MEDIAMAILOVERIP		139
           #define IFTYPE_DTM		140
           #define IFTYPE_DCN		141
           #define IFTYPE_IPFORWARD		142
           #define IFTYPE_MSDSL		143
           #define IFTYPE_IEEE1394		144
           #define IFTYPE_IF_GSN		145
           #define IFTYPE_DVBRCCMACLAYER		146
           #define IFTYPE_DVBRCCDOWNSTREAM		147
           #define IFTYPE_DVBRCCUPSTREAM		148
           #define IFTYPE_ATMVIRTUAL		149
           #define IFTYPE_MPLSTUNNEL		150
           #define IFTYPE_SRP		151
           #define IFTYPE_VOICEOVERATM		152
           #define IFTYPE_VOICEOVERFRAMERELAY		153
           #define IFTYPE_IDSL		154
           #define IFTYPE_COMPOSITELINK		155
           #define IFTYPE_SS7SIGLINK		156
           #define IFTYPE_PROPWIRELESSP2P		157
           #define IFTYPE_FRFORWARD		158
           #define IFTYPE_RFC1483		159
           #define IFTYPE_USB		160
           #define IFTYPE_IEEE8023ADLAG		161
           #define IFTYPE_BGPPOLICYACCOUNTING		162
           #define IFTYPE_FRF16MFRBUNDLE		163
           #define IFTYPE_H323GATEKEEPER		164
           #define IFTYPE_H323PROXY		165
           #define IFTYPE_MPLS		166
           #define IFTYPE_MFSIGLINK		167
           #define IFTYPE_HDSL2		168
           #define IFTYPE_SHDSL		169
           #define IFTYPE_DS1FDL		170
           #define IFTYPE_POS		171
           #define IFTYPE_DVBASIIN		172
           #define IFTYPE_DVBASIOUT		173
           #define IFTYPE_PLC		174
           #define IFTYPE_NFAS		175
           #define IFTYPE_TR008		176
           #define IFTYPE_GR303RDT		177
           #define IFTYPE_GR303IDT		178
           #define IFTYPE_ISUP		179
           #define IFTYPE_PROPDOCSWIRELESSMACLAYER		180
           #define IFTYPE_PROPDOCSWIRELESSDOWNSTREAM		181
           #define IFTYPE_PROPDOCSWIRELESSUPSTREAM		182
           #define IFTYPE_HIPERLAN2		183
           #define IFTYPE_PROPBWAP2MP		184
           #define IFTYPE_SONETOVERHEADCHANNEL		185
           #define IFTYPE_DIGITALWRAPPEROVERHEADCHANNEL		186
           #define IFTYPE_AAL2		187
           #define IFTYPE_RADIOMAC		188
           #define IFTYPE_ATMRADIO		189
           #define IFTYPE_IMT		190
           #define IFTYPE_MVL		191
           #define IFTYPE_REACHDSL		192
           #define IFTYPE_FRDLCIENDPT		193
           #define IFTYPE_ATMVCIENDPT		194
           #define IFTYPE_OPTICALCHANNEL		195
           #define IFTYPE_OPTICALTRANSPORT		196
           #define IFTYPE_PROPATM		197
           #define IFTYPE_VOICEOVERCABLE		198
           #define IFTYPE_INFINIBAND		199
           #define IFTYPE_TELINK		200
           #define IFTYPE_Q2931		201
           #define IFTYPE_VIRTUALTG		202
           #define IFTYPE_SIPTG		203
           #define IFTYPE_SIPSIG		204
           #define IFTYPE_DOCSCABLEUPSTREAMCHANNEL		205
           #define IFTYPE_ECONET		206
           #define IFTYPE_PON155		207
           #define IFTYPE_PON622		208
           #define IFTYPE_BRIDGE		209
           #define IFTYPE_LINEGROUP		210
           #define IFTYPE_VOICEEMFGD		211
           #define IFTYPE_VOICEFGDEANA		212
           #define IFTYPE_VOICEDID		213
           #define IFTYPE_MPEGTRANSPORT		214
           #define IFTYPE_SIXTOFOUR		215
           #define IFTYPE_GTP		216
           #define IFTYPE_PDNETHERLOOP1		217
           #define IFTYPE_PDNETHERLOOP2		218
           #define IFTYPE_OPTICALCHANNELGROUP		219
           #define IFTYPE_HOMEPNA		220
           #define IFTYPE_GFP		221
           #define IFTYPE_CISCOISLVLAN		222
           #define IFTYPE_ACTELISMETALOOP		223
           #define IFTYPE_FCIPLINK		224
           #define IFTYPE_RPR		225
           #define IFTYPE_QAM		226
           #define IFTYPE_LMP		227
           #define IFTYPE_CBLVECTASTAR		228
           #define IFTYPE_DOCSCABLEMCMTSDOWNSTREAM		229
           #define IFTYPE_ADSL2		230

/* enums for column ifAdminStatus */
           #define IFADMINSTATUS_UP		1
           #define IFADMINSTATUS_DOWN		2
           #define IFADMINSTATUS_TESTING		3

/* enums for column ifOperStatus */
           #define IFOPERSTATUS_UP		1
           #define IFOPERSTATUS_DOWN		2
           #define IFOPERSTATUS_TESTING		3
           #define IFOPERSTATUS_UNKNOWN		4
           #define IFOPERSTATUS_DORMANT		5
           #define IFOPERSTATUS_NOTPRESENT		6
           #define IFOPERSTATUS_LOWERLAYERDOWN		7

/* enums for column ipRouteType */
           #define IPROUTETYPE_OTHER		1
           #define IPROUTETYPE_INVALID		2
           #define IPROUTETYPE_DIRECT		3
           #define IPROUTETYPE_INDIRECT		4

/* enums for column ipRouteProto */
           #define IPROUTEPROTO_OTHER		1
           #define IPROUTEPROTO_LOCAL		2
           #define IPROUTEPROTO_NETMGMT		3
           #define IPROUTEPROTO_ICMP		4
           #define IPROUTEPROTO_EGP		5
           #define IPROUTEPROTO_GGP		6
           #define IPROUTEPROTO_HELLO		7
           #define IPROUTEPROTO_RIP		8
           #define IPROUTEPROTO_IS_IS		9
           #define IPROUTEPROTO_ES_IS		10
           #define IPROUTEPROTO_CISCOIGRP		11
           #define IPROUTEPROTO_BBNSPFIGP		12
           #define IPROUTEPROTO_OSPF		13
           #define IPROUTEPROTO_BGP		14

/* enums for column ipNetToMediaType */
           #define IPNETTOMEDIATYPE_OTHER		1
           #define IPNETTOMEDIATYPE_INVALID		2
           #define IPNETTOMEDIATYPE_DYNAMIC		3
           #define IPNETTOMEDIATYPE_STATIC		4

/* enums for column tcpConnState */
           #define TCPCONNSTATE_CLOSED		1
           #define TCPCONNSTATE_LISTEN		2
           #define TCPCONNSTATE_SYNSENT		3
           #define TCPCONNSTATE_SYNRECEIVED		4
           #define TCPCONNSTATE_ESTABLISHED		5
           #define TCPCONNSTATE_FINWAIT1		6
           #define TCPCONNSTATE_FINWAIT2		7
           #define TCPCONNSTATE_CLOSEWAIT		8
           #define TCPCONNSTATE_LASTACK		9
           #define TCPCONNSTATE_CLOSING		10
           #define TCPCONNSTATE_TIMEWAIT		11
           #define TCPCONNSTATE_DELETETCB		12

/* enums for column egpNeighState */
           #define EGPNEIGHSTATE_IDLE		1
           #define EGPNEIGHSTATE_ACQUISITION		2
           #define EGPNEIGHSTATE_DOWN		3
           #define EGPNEIGHSTATE_UP		4
           #define EGPNEIGHSTATE_CEASE		5

/* enums for column egpNeighMode */
           #define EGPNEIGHMODE_ACTIVE		1
           #define EGPNEIGHMODE_PASSIVE		2

/* enums for column egpNeighEventTrigger */
           #define EGPNEIGHEVENTTRIGGER_START		1
           #define EGPNEIGHEVENTTRIGGER_STOP		2

/* enums for column rs232PortType */
           #define RS232PORTTYPE_OTHER		1
           #define RS232PORTTYPE_RS232		2
           #define RS232PORTTYPE_RS422		3
           #define RS232PORTTYPE_RS423		4
           #define RS232PORTTYPE_V35		5
           #define RS232PORTTYPE_X21		6

/* enums for column rs232PortInFlowType */
           #define RS232PORTINFLOWTYPE_NONE		1
           #define RS232PORTINFLOWTYPE_CTSRTS		2
           #define RS232PORTINFLOWTYPE_DSRDTR		3

/* enums for column rs232PortOutFlowType */
           #define RS232PORTOUTFLOWTYPE_NONE		1
           #define RS232PORTOUTFLOWTYPE_CTSRTS		2
           #define RS232PORTOUTFLOWTYPE_DSRDTR		3

/* enums for column rs232AsyncPortStopBits */
           #define RS232ASYNCPORTSTOPBITS_ONE		1
           #define RS232ASYNCPORTSTOPBITS_TWO		2
           #define RS232ASYNCPORTSTOPBITS_ONEANDHALF		3
           #define RS232ASYNCPORTSTOPBITS_DYNAMIC		4

/* enums for column rs232AsyncPortParity */
           #define RS232ASYNCPORTPARITY_NONE		1
           #define RS232ASYNCPORTPARITY_ODD		2
           #define RS232ASYNCPORTPARITY_EVEN		3
           #define RS232ASYNCPORTPARITY_MARK		4
           #define RS232ASYNCPORTPARITY_SPACE		5

/* enums for column rs232AsyncPortAutobaud */
           #define RS232ASYNCPORTAUTOBAUD_ENABLED		1
           #define RS232ASYNCPORTAUTOBAUD_DISABLED		2

/* enums for column rs232SyncPortClockSource */
           #define RS232SYNCPORTCLOCKSOURCE_INTERNAL		1
           #define RS232SYNCPORTCLOCKSOURCE_EXTERNAL		2
           #define RS232SYNCPORTCLOCKSOURCE_SPLIT		3

/* enums for column rs232SyncPortRole */
           #define RS232SYNCPORTROLE_DTE		1
           #define RS232SYNCPORTROLE_DCE		2

/* enums for column rs232SyncPortEncoding */
           #define RS232SYNCPORTENCODING_NRZ		1
           #define RS232SYNCPORTENCODING_NRZI		2

/* enums for column rs232SyncPortRTSControl */
           #define RS232SYNCPORTRTSCONTROL_CONTROLLED		1
           #define RS232SYNCPORTRTSCONTROL_CONSTANT		2

/* enums for column rs232SyncPortMode */
           #define RS232SYNCPORTMODE_FDX		1
           #define RS232SYNCPORTMODE_HDX		2
           #define RS232SYNCPORTMODE_SIMPLEX_RECEIVE		3
           #define RS232SYNCPORTMODE_SIMPLEX_SEND		4

/* enums for column rs232SyncPortIdlePattern */
           #define RS232SYNCPORTIDLEPATTERN_MARK		1
           #define RS232SYNCPORTIDLEPATTERN_SPACE		2

/* enums for column rs232InSigName */
           #define RS232INSIGNAME_RTS		1
           #define RS232INSIGNAME_CTS		2
           #define RS232INSIGNAME_DSR		3
           #define RS232INSIGNAME_DTR		4
           #define RS232INSIGNAME_RI		5
           #define RS232INSIGNAME_DCD		6
           #define RS232INSIGNAME_SQ		7
           #define RS232INSIGNAME_SRS		8
           #define RS232INSIGNAME_SRTS		9
           #define RS232INSIGNAME_SCTS		10
           #define RS232INSIGNAME_SDCD		11

/* enums for column rs232InSigState */
           #define RS232INSIGSTATE_NONE		1
           #define RS232INSIGSTATE_ON		2
           #define RS232INSIGSTATE_OFF		3

/* enums for column rs232OutSigName */
           #define RS232OUTSIGNAME_RTS		1
           #define RS232OUTSIGNAME_CTS		2
           #define RS232OUTSIGNAME_DSR		3
           #define RS232OUTSIGNAME_DTR		4
           #define RS232OUTSIGNAME_RI		5
           #define RS232OUTSIGNAME_DCD		6
           #define RS232OUTSIGNAME_SQ		7
           #define RS232OUTSIGNAME_SRS		8
           #define RS232OUTSIGNAME_SRTS		9
           #define RS232OUTSIGNAME_SCTS		10
           #define RS232OUTSIGNAME_SDCD		11

/* enums for column rs232OutSigState */
           #define RS232OUTSIGSTATE_NONE		1
           #define RS232OUTSIGSTATE_ON		2
           #define RS232OUTSIGSTATE_OFF		3

/* enums for column ifLinkUpDownTrapEnable */
           #define IFLINKUPDOWNTRAPENABLE_ENABLED		1
           #define IFLINKUPDOWNTRAPENABLE_DISABLED		2

/* enums for column ifPromiscuousMode */
           #define IFPROMISCUOUSMODE_TRUE		1
           #define IFPROMISCUOUSMODE_FALSE		2

/* enums for column ifConnectorPresent */
           #define IFCONNECTORPRESENT_TRUE		1
           #define IFCONNECTORPRESENT_FALSE		2

/* enums for column ifStackStatus */
           #define IFSTACKSTATUS_ACTIVE		1
           #define IFSTACKSTATUS_NOTINSERVICE		2
           #define IFSTACKSTATUS_NOTREADY		3
           #define IFSTACKSTATUS_CREATEANDGO		4
           #define IFSTACKSTATUS_CREATEANDWAIT		5
           #define IFSTACKSTATUS_DESTROY		6

/* enums for column ifTestStatus */
           #define IFTESTSTATUS_NOTINUSE		1
           #define IFTESTSTATUS_INUSE		2

/* enums for column ifTestResult */
           #define IFTESTRESULT_NONE		1
           #define IFTESTRESULT_SUCCESS		2
           #define IFTESTRESULT_INPROGRESS		3
           #define IFTESTRESULT_NOTSUPPORTED		4
           #define IFTESTRESULT_UNABLETORUN		5
           #define IFTESTRESULT_ABORTED		6
           #define IFTESTRESULT_FAILED		7

/* enums for column ifRcvAddressStatus */
           #define IFRCVADDRESSSTATUS_ACTIVE		1
           #define IFRCVADDRESSSTATUS_NOTINSERVICE		2
           #define IFRCVADDRESSSTATUS_NOTREADY		3
           #define IFRCVADDRESSSTATUS_CREATEANDGO		4
           #define IFRCVADDRESSSTATUS_CREATEANDWAIT		5
           #define IFRCVADDRESSSTATUS_DESTROY		6

/* enums for column ifRcvAddressType */
           #define IFRCVADDRESSTYPE_OTHER		1
           #define IFRCVADDRESSTYPE_VOLATILE		2
           #define IFRCVADDRESSTYPE_NONVOLATILE		3


/* enums for scalar ipForwarding */
#define IPFORWARDING_FORWARDING		1
#define IPFORWARDING_NOT_FORWARDING		2

/* enums for scalar tcpRtoAlgorithm */
#define TCPRTOALGORITHM_OTHER		1
#define TCPRTOALGORITHM_CONSTANT		2
#define TCPRTOALGORITHM_RSRE		3
#define TCPRTOALGORITHM_VANJ		4

/* enums for scalar snmpEnableAuthenTraps */
#define SNMPENABLEAUTHENTRAPS_ENABLED		1
#define SNMPENABLEAUTHENTRAPS_DISABLED		2

#endif /* MIB-2_ENUMS_H */
