/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate_access.conf 15179 2006-09-08 15:44:37Z dts12 $
 */
#ifndef MIB-2_H
#define MIB-2_H

/** other required module components */
config_require(mib-2_access)
config_require(mib-2_checkfns)

/* function declarations */
void init_mib-2(void);
void initialize_table_sysORTable(void);
Netsnmp_Node_Handler sysORTable_handler;

void initialize_table_ifTable(void);
Netsnmp_Node_Handler ifTable_handler;

void initialize_table_atTable(void);
Netsnmp_Node_Handler atTable_handler;

void initialize_table_ipAddrTable(void);
Netsnmp_Node_Handler ipAddrTable_handler;

void initialize_table_ipRouteTable(void);
Netsnmp_Node_Handler ipRouteTable_handler;

void initialize_table_ipNetToMediaTable(void);
Netsnmp_Node_Handler ipNetToMediaTable_handler;

void initialize_table_tcpConnTable(void);
Netsnmp_Node_Handler tcpConnTable_handler;

void initialize_table_udpTable(void);
Netsnmp_Node_Handler udpTable_handler;

void initialize_table_egpNeighTable(void);
Netsnmp_Node_Handler egpNeighTable_handler;

void initialize_table_rs232PortTable(void);
Netsnmp_Node_Handler rs232PortTable_handler;

void initialize_table_rs232AsyncPortTable(void);
Netsnmp_Node_Handler rs232AsyncPortTable_handler;

void initialize_table_rs232SyncPortTable(void);
Netsnmp_Node_Handler rs232SyncPortTable_handler;

void initialize_table_rs232InSigTable(void);
Netsnmp_Node_Handler rs232InSigTable_handler;

void initialize_table_rs232OutSigTable(void);
Netsnmp_Node_Handler rs232OutSigTable_handler;

void initialize_table_ifXTable(void);
Netsnmp_Node_Handler ifXTable_handler;

void initialize_table_ifStackTable(void);
Netsnmp_Node_Handler ifStackTable_handler;

void initialize_table_ifTestTable(void);
Netsnmp_Node_Handler ifTestTable_handler;

void initialize_table_ifRcvAddressTable(void);
Netsnmp_Node_Handler ifRcvAddressTable_handler;


/* column number definitions for table sysORTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table ifTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table atTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table ipAddrTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table ipRouteTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table ipNetToMediaTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table tcpConnTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table udpTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table egpNeighTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table rs232PortTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table rs232AsyncPortTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table rs232SyncPortTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table rs232InSigTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table rs232OutSigTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table ifXTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table ifStackTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table ifTestTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"


/* column number definitions for table ifRcvAddressTable */
#include "mib-2_columns.h"

/* enum definions */
#include "mib-2_enums.h"

#endif /** MIB-2_H */
