/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf 7011 2002-05-08 05:42:47Z hardaker $
 */
#ifndef RS232_COLUMNS_H
#define RS232_COLUMNS_H

/* column number definitions for table rs232PortTable */
       #define COLUMN_RS232PORTINDEX		1
       #define COLUMN_RS232PORTTYPE		2
       #define COLUMN_RS232PORTINSIGNUMBER		3
       #define COLUMN_RS232PORTOUTSIGNUMBER		4
       #define COLUMN_RS232PORTINSPEED		5
       #define COLUMN_RS232PORTOUTSPEED		6
       #define COLUMN_RS232PORTINFLOWTYPE		7
       #define COLUMN_RS232PORTOUTFLOWTYPE		8

/* column number definitions for table rs232AsyncPortTable */
       #define COLUMN_RS232ASYNCPORTINDEX		1
       #define COLUMN_RS232ASYNCPORTBITS		2
       #define COLUMN_RS232ASYNCPORTSTOPBITS		3
       #define COLUMN_RS232ASYNCPORTPARITY		4
       #define COLUMN_RS232ASYNCPORTAUTOBAUD		5
       #define COLUMN_RS232ASYNCPORTPARITYERRS		6
       #define COLUMN_RS232ASYNCPORTFRAMINGERRS		7
       #define COLUMN_RS232ASYNCPORTOVERRUNERRS		8

/* column number definitions for table rs232SyncPortTable */
       #define COLUMN_RS232SYNCPORTINDEX		1
       #define COLUMN_RS232SYNCPORTCLOCKSOURCE		2
       #define COLUMN_RS232SYNCPORTFRAMECHECKERRS		3
       #define COLUMN_RS232SYNCPORTTRANSMITUNDERRUNERRS		4
       #define COLUMN_RS232SYNCPORTRECEIVEOVERRUNERRS		5
       #define COLUMN_RS232SYNCPORTINTERRUPTEDFRAMES		6
       #define COLUMN_RS232SYNCPORTABORTEDFRAMES		7
       #define COLUMN_RS232SYNCPORTROLE		8
       #define COLUMN_RS232SYNCPORTENCODING		9
       #define COLUMN_RS232SYNCPORTRTSCONTROL		10
       #define COLUMN_RS232SYNCPORTRTSCTSDELAY		11
       #define COLUMN_RS232SYNCPORTMODE		12
       #define COLUMN_RS232SYNCPORTIDLEPATTERN		13
       #define COLUMN_RS232SYNCPORTMINFLAGS		14

/* column number definitions for table rs232InSigTable */
       #define COLUMN_RS232INSIGPORTINDEX		1
       #define COLUMN_RS232INSIGNAME		2
       #define COLUMN_RS232INSIGSTATE		3
       #define COLUMN_RS232INSIGCHANGES		4

/* column number definitions for table rs232OutSigTable */
       #define COLUMN_RS232OUTSIGPORTINDEX		1
       #define COLUMN_RS232OUTSIGNAME		2
       #define COLUMN_RS232OUTSIGSTATE		3
       #define COLUMN_RS232OUTSIGCHANGES		4
#endif /* RS232_COLUMNS_H */
