/*
 * Note: this file originally auto-generated by mib2c using
 *        : : mib2c.check_values_local.conf 10232 2004-05-04 23:35:32Z hardaker $
 * 
 */
#ifndef RS232_CHECKFNS_H
#define RS232_CHECKFNS_H

/* these functions are designed to check incoming values for 
columns in the rs232PortTable table for legality with respect to 
datatype and value according to local conventions.  You should modify
them as appropriate.  They will be called from parent check_value
functions that are auto-generated using mib2c and the parent functions
should NOT be modified.
 */

    int check_rs232PortInSpeed_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232PortOutSpeed_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232PortInFlowType_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232PortOutFlowType_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for 
columns in the rs232AsyncPortTable table for legality with respect to 
datatype and value according to local conventions.  You should modify
them as appropriate.  They will be called from parent check_value
functions that are auto-generated using mib2c and the parent functions
should NOT be modified.
 */

    int check_rs232AsyncPortBits_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232AsyncPortStopBits_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232AsyncPortParity_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232AsyncPortAutobaud_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for 
columns in the rs232SyncPortTable table for legality with respect to 
datatype and value according to local conventions.  You should modify
them as appropriate.  They will be called from parent check_value
functions that are auto-generated using mib2c and the parent functions
should NOT be modified.
 */

    int check_rs232SyncPortClockSource_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232SyncPortRole_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232SyncPortEncoding_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232SyncPortRTSControl_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232SyncPortRTSCTSDelay_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232SyncPortMode_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232SyncPortIdlePattern_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
    int check_rs232SyncPortMinFlags_local(int type, long *val, size_t val_len, long *old_val, size_t old_val_len);
/* these functions are designed to check incoming values for 
columns in the rs232InSigTable table for legality with respect to 
datatype and value according to local conventions.  You should modify
them as appropriate.  They will be called from parent check_value
functions that are auto-generated using mib2c and the parent functions
should NOT be modified.
 */

/* these functions are designed to check incoming values for 
columns in the rs232OutSigTable table for legality with respect to 
datatype and value according to local conventions.  You should modify
them as appropriate.  They will be called from parent check_value
functions that are auto-generated using mib2c and the parent functions
should NOT be modified.
 */


#endif /* RS232_CHECKFNS_H */

