/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.access_functions.conf 11358 2004-10-14 12:57:34Z dts12 $
 */
#ifndef RS232_ACCESS_H
#define RS232_ACCESS_H

/** User-defined data access functions for data in table rs232PortTable */
/** row level accessors */
Netsnmp_First_Data_Point  rs232PortTable_get_first_data_point;
Netsnmp_Next_Data_Point   rs232PortTable_get_next_data_point;
int rs232PortTable_commit_row(void **my_data_context, int new_or_del);
void * rs232PortTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      long *get_rs232PortIndex(void *data_context, size_t *ret_len);
      long *get_rs232PortType(void *data_context, size_t *ret_len);
      long *get_rs232PortInSigNumber(void *data_context, size_t *ret_len);
      long *get_rs232PortOutSigNumber(void *data_context, size_t *ret_len);
      long *get_rs232PortInSpeed(void *data_context, size_t *ret_len);
      int set_rs232PortInSpeed(void *data_context, long *val, size_t val_len);
      long *get_rs232PortOutSpeed(void *data_context, size_t *ret_len);
      int set_rs232PortOutSpeed(void *data_context, long *val, size_t val_len);
      long *get_rs232PortInFlowType(void *data_context, size_t *ret_len);
      int set_rs232PortInFlowType(void *data_context, long *val, size_t val_len);
      long *get_rs232PortOutFlowType(void *data_context, size_t *ret_len);
      int set_rs232PortOutFlowType(void *data_context, long *val, size_t val_len);
/** User-defined data access functions for data in table rs232AsyncPortTable */
/** row level accessors */
Netsnmp_First_Data_Point  rs232AsyncPortTable_get_first_data_point;
Netsnmp_Next_Data_Point   rs232AsyncPortTable_get_next_data_point;
int rs232AsyncPortTable_commit_row(void **my_data_context, int new_or_del);
void * rs232AsyncPortTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      long *get_rs232AsyncPortIndex(void *data_context, size_t *ret_len);
      long *get_rs232AsyncPortBits(void *data_context, size_t *ret_len);
      int set_rs232AsyncPortBits(void *data_context, long *val, size_t val_len);
      long *get_rs232AsyncPortStopBits(void *data_context, size_t *ret_len);
      int set_rs232AsyncPortStopBits(void *data_context, long *val, size_t val_len);
      long *get_rs232AsyncPortParity(void *data_context, size_t *ret_len);
      int set_rs232AsyncPortParity(void *data_context, long *val, size_t val_len);
      long *get_rs232AsyncPortAutobaud(void *data_context, size_t *ret_len);
      int set_rs232AsyncPortAutobaud(void *data_context, long *val, size_t val_len);
      u_long *get_rs232AsyncPortParityErrs(void *data_context, size_t *ret_len);
      u_long *get_rs232AsyncPortFramingErrs(void *data_context, size_t *ret_len);
      u_long *get_rs232AsyncPortOverrunErrs(void *data_context, size_t *ret_len);
/** User-defined data access functions for data in table rs232SyncPortTable */
/** row level accessors */
Netsnmp_First_Data_Point  rs232SyncPortTable_get_first_data_point;
Netsnmp_Next_Data_Point   rs232SyncPortTable_get_next_data_point;
int rs232SyncPortTable_commit_row(void **my_data_context, int new_or_del);
void * rs232SyncPortTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      long *get_rs232SyncPortIndex(void *data_context, size_t *ret_len);
      long *get_rs232SyncPortClockSource(void *data_context, size_t *ret_len);
      int set_rs232SyncPortClockSource(void *data_context, long *val, size_t val_len);
      u_long *get_rs232SyncPortFrameCheckErrs(void *data_context, size_t *ret_len);
      u_long *get_rs232SyncPortTransmitUnderrunErrs(void *data_context, size_t *ret_len);
      u_long *get_rs232SyncPortReceiveOverrunErrs(void *data_context, size_t *ret_len);
      u_long *get_rs232SyncPortInterruptedFrames(void *data_context, size_t *ret_len);
      u_long *get_rs232SyncPortAbortedFrames(void *data_context, size_t *ret_len);
      long *get_rs232SyncPortRole(void *data_context, size_t *ret_len);
      int set_rs232SyncPortRole(void *data_context, long *val, size_t val_len);
      long *get_rs232SyncPortEncoding(void *data_context, size_t *ret_len);
      int set_rs232SyncPortEncoding(void *data_context, long *val, size_t val_len);
      long *get_rs232SyncPortRTSControl(void *data_context, size_t *ret_len);
      int set_rs232SyncPortRTSControl(void *data_context, long *val, size_t val_len);
      long *get_rs232SyncPortRTSCTSDelay(void *data_context, size_t *ret_len);
      int set_rs232SyncPortRTSCTSDelay(void *data_context, long *val, size_t val_len);
      long *get_rs232SyncPortMode(void *data_context, size_t *ret_len);
      int set_rs232SyncPortMode(void *data_context, long *val, size_t val_len);
      long *get_rs232SyncPortIdlePattern(void *data_context, size_t *ret_len);
      int set_rs232SyncPortIdlePattern(void *data_context, long *val, size_t val_len);
      long *get_rs232SyncPortMinFlags(void *data_context, size_t *ret_len);
      int set_rs232SyncPortMinFlags(void *data_context, long *val, size_t val_len);
/** User-defined data access functions for data in table rs232InSigTable */
/** row level accessors */
Netsnmp_First_Data_Point  rs232InSigTable_get_first_data_point;
Netsnmp_Next_Data_Point   rs232InSigTable_get_next_data_point;
int rs232InSigTable_commit_row(void **my_data_context, int new_or_del);
void * rs232InSigTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      long *get_rs232InSigPortIndex(void *data_context, size_t *ret_len);
      long *get_rs232InSigName(void *data_context, size_t *ret_len);
      long *get_rs232InSigState(void *data_context, size_t *ret_len);
      u_long *get_rs232InSigChanges(void *data_context, size_t *ret_len);
/** User-defined data access functions for data in table rs232OutSigTable */
/** row level accessors */
Netsnmp_First_Data_Point  rs232OutSigTable_get_first_data_point;
Netsnmp_Next_Data_Point   rs232OutSigTable_get_next_data_point;
int rs232OutSigTable_commit_row(void **my_data_context, int new_or_del);
void * rs232OutSigTable_create_data_context(netsnmp_variable_list *index_data, int column);

/** column accessors */
      long *get_rs232OutSigPortIndex(void *data_context, size_t *ret_len);
      long *get_rs232OutSigName(void *data_context, size_t *ret_len);
      long *get_rs232OutSigState(void *data_context, size_t *ret_len);
      u_long *get_rs232OutSigChanges(void *data_context, size_t *ret_len);

#endif /* RS232_ACCESS_H */
