/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate_access.conf 15179 2006-09-08 15:44:37Z dts12 $
 */
#ifndef RS232_H
#define RS232_H

/** other required module components */
//config_require(rs232_access)
//config_require(rs232_checkfns)

/* function declarations */
void init_rs232(void);
void initialize_table_rs232PortTable(void);
Netsnmp_Node_Handler rs232PortTable_handler;

void initialize_table_rs232AsyncPortTable(void);
Netsnmp_Node_Handler rs232AsyncPortTable_handler;

void initialize_table_rs232SyncPortTable(void);
Netsnmp_Node_Handler rs232SyncPortTable_handler;

void initialize_table_rs232InSigTable(void);
Netsnmp_Node_Handler rs232InSigTable_handler;

void initialize_table_rs232OutSigTable(void);
Netsnmp_Node_Handler rs232OutSigTable_handler;

Netsnmp_Node_Handler handle_rs232Number;

/* column number definitions for table rs232PortTable */
#include "rs232_columns.h"

/* enum definions */
#include "rs232_enums.h"


/* column number definitions for table rs232AsyncPortTable */
#include "rs232_columns.h"

/* enum definions */
#include "rs232_enums.h"


/* column number definitions for table rs232SyncPortTable */
#include "rs232_columns.h"

/* enum definions */
#include "rs232_enums.h"


/* column number definitions for table rs232InSigTable */
#include "rs232_columns.h"

/* enum definions */
#include "rs232_enums.h"


/* column number definitions for table rs232OutSigTable */
#include "rs232_columns.h"

/* enum definions */
#include "rs232_enums.h"

#endif /** RS232_H */
