/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "rs232.h"

/** Initializes the rs232 module */
void
init_rs232(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_rs232PortTable();
    initialize_table_rs232AsyncPortTable();
    initialize_table_rs232SyncPortTable();
    initialize_table_rs232InSigTable();
    initialize_table_rs232OutSigTable();
}

  # Determine the first/last column names

/** Initialize the rs232PortTable table by defining its contents and how it's structured */
void
initialize_table_rs232PortTable(void)
{
    static oid rs232PortTable_oid[] = {1,3,6,1,2,1,10,33,2};
    size_t rs232PortTable_oid_len   = OID_LENGTH(rs232PortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "rs232PortTable",     rs232PortTable_handler,
              rs232PortTable_oid, rs232PortTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: rs232PortIndex */
                           0);
    table_info->min_column = COLUMN_RS232PORTINDEX;
    table_info->max_column = COLUMN_RS232PORTOUTFLOWTYPE;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = rs232PortTable_get_first_data_point;
    iinfo->get_next_data_point  = rs232PortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct rs232PortTable_entry {
    /* Index values */
    long rs232PortIndex;

    /* Column values */
    long rs232PortIndex;
    long rs232PortType;
    long rs232PortInSigNumber;
    long rs232PortOutSigNumber;
    long rs232PortInSpeed;
    long old_rs232PortInSpeed;
    long rs232PortOutSpeed;
    long old_rs232PortOutSpeed;
    long rs232PortInFlowType;
    long old_rs232PortInFlowType;
    long rs232PortOutFlowType;
    long old_rs232PortOutFlowType;

    /* Illustrate using a simple linked list */
    int   valid;
    struct rs232PortTable_entry *next;
};

struct rs232PortTable_entry  *rs232PortTable_head;

/* create a new row in the (unsorted) table */
struct rs232PortTable_entry *
rs232PortTable_createEntry(
                 long  rs232PortIndex,
                ) {
    struct rs232PortTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct rs232PortTable_entry);
    if (!entry)
        return NULL;

    entry->rs232PortIndex = rs232PortIndex;
    entry->next = rs232PortTable_head;
    rs232PortTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
rs232PortTable_removeEntry( struct rs232PortTable_entry *entry ) {
    struct rs232PortTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = rs232PortTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        rs232PortTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
rs232PortTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = rs232PortTable_head;
    return rs232PortTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
rs232PortTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct rs232PortTable_entry *entry = (struct rs232PortTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rs232PortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the rs232PortTable table */
int
rs232PortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct rs232PortTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232PortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232PORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortIndex);
                break;
            case COLUMN_RS232PORTTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortType);
                break;
            case COLUMN_RS232PORTINSIGNUMBER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortInSigNumber);
                break;
            case COLUMN_RS232PORTOUTSIGNUMBER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortOutSigNumber);
                break;
            case COLUMN_RS232PORTINSPEED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortInSpeed);
                break;
            case COLUMN_RS232PORTOUTSPEED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortOutSpeed);
                break;
            case COLUMN_RS232PORTINFLOWTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortInFlowType);
                break;
            case COLUMN_RS232PORTOUTFLOWTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortOutFlowType);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232PortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232PORTINSPEED:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232PORTOUTSPEED:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232PORTINFLOWTYPE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232PORTOUTFLOWTYPE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232PortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232PORTINSPEED:
                table_entry->old_rs232PortInSpeed = table_entry->rs232PortInSpeed;
                table_entry->rs232PortInSpeed     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232PORTOUTSPEED:
                table_entry->old_rs232PortOutSpeed = table_entry->rs232PortOutSpeed;
                table_entry->rs232PortOutSpeed     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232PORTINFLOWTYPE:
                table_entry->old_rs232PortInFlowType = table_entry->rs232PortInFlowType;
                table_entry->rs232PortInFlowType     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232PORTOUTFLOWTYPE:
                table_entry->old_rs232PortOutFlowType = table_entry->rs232PortOutFlowType;
                table_entry->rs232PortOutFlowType     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232PortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232PORTINSPEED:
                table_entry->rs232PortInSpeed     = table_entry->old_rs232PortInSpeed;
                table_entry->old_rs232PortInSpeed = 0;
                break;
            case COLUMN_RS232PORTOUTSPEED:
                table_entry->rs232PortOutSpeed     = table_entry->old_rs232PortOutSpeed;
                table_entry->old_rs232PortOutSpeed = 0;
                break;
            case COLUMN_RS232PORTINFLOWTYPE:
                table_entry->rs232PortInFlowType     = table_entry->old_rs232PortInFlowType;
                table_entry->old_rs232PortInFlowType = 0;
                break;
            case COLUMN_RS232PORTOUTFLOWTYPE:
                table_entry->rs232PortOutFlowType     = table_entry->old_rs232PortOutFlowType;
                table_entry->old_rs232PortOutFlowType = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
  # Determine the first/last column names

/** Initialize the rs232AsyncPortTable table by defining its contents and how it's structured */
void
initialize_table_rs232AsyncPortTable(void)
{
    static oid rs232AsyncPortTable_oid[] = {1,3,6,1,2,1,10,33,3};
    size_t rs232AsyncPortTable_oid_len   = OID_LENGTH(rs232AsyncPortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "rs232AsyncPortTable",     rs232AsyncPortTable_handler,
              rs232AsyncPortTable_oid, rs232AsyncPortTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: rs232AsyncPortIndex */
                           0);
    table_info->min_column = COLUMN_RS232ASYNCPORTINDEX;
    table_info->max_column = COLUMN_RS232ASYNCPORTOVERRUNERRS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = rs232AsyncPortTable_get_first_data_point;
    iinfo->get_next_data_point  = rs232AsyncPortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct rs232AsyncPortTable_entry {
    /* Index values */
    long rs232AsyncPortIndex;

    /* Column values */
    long rs232AsyncPortIndex;
    long rs232AsyncPortBits;
    long old_rs232AsyncPortBits;
    long rs232AsyncPortStopBits;
    long old_rs232AsyncPortStopBits;
    long rs232AsyncPortParity;
    long old_rs232AsyncPortParity;
    long rs232AsyncPortAutobaud;
    long old_rs232AsyncPortAutobaud;
    u_long rs232AsyncPortParityErrs;
    u_long rs232AsyncPortFramingErrs;
    u_long rs232AsyncPortOverrunErrs;

    /* Illustrate using a simple linked list */
    int   valid;
    struct rs232AsyncPortTable_entry *next;
};

struct rs232AsyncPortTable_entry  *rs232AsyncPortTable_head;

/* create a new row in the (unsorted) table */
struct rs232AsyncPortTable_entry *
rs232AsyncPortTable_createEntry(
                 long  rs232AsyncPortIndex,
                ) {
    struct rs232AsyncPortTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct rs232AsyncPortTable_entry);
    if (!entry)
        return NULL;

    entry->rs232AsyncPortIndex = rs232AsyncPortIndex;
    entry->next = rs232AsyncPortTable_head;
    rs232AsyncPortTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
rs232AsyncPortTable_removeEntry( struct rs232AsyncPortTable_entry *entry ) {
    struct rs232AsyncPortTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = rs232AsyncPortTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        rs232AsyncPortTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
rs232AsyncPortTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = rs232AsyncPortTable_head;
    return rs232AsyncPortTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
rs232AsyncPortTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct rs232AsyncPortTable_entry *entry = (struct rs232AsyncPortTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rs232AsyncPortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the rs232AsyncPortTable table */
int
rs232AsyncPortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct rs232AsyncPortTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232AsyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232ASYNCPORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232AsyncPortIndex);
                break;
            case COLUMN_RS232ASYNCPORTBITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232AsyncPortBits);
                break;
            case COLUMN_RS232ASYNCPORTSTOPBITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232AsyncPortStopBits);
                break;
            case COLUMN_RS232ASYNCPORTPARITY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232AsyncPortParity);
                break;
            case COLUMN_RS232ASYNCPORTAUTOBAUD:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232AsyncPortAutobaud);
                break;
            case COLUMN_RS232ASYNCPORTPARITYERRS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232AsyncPortParityErrs);
                break;
            case COLUMN_RS232ASYNCPORTFRAMINGERRS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232AsyncPortFramingErrs);
                break;
            case COLUMN_RS232ASYNCPORTOVERRUNERRS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232AsyncPortOverrunErrs);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232AsyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232ASYNCPORTBITS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232ASYNCPORTSTOPBITS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232ASYNCPORTPARITY:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232ASYNCPORTAUTOBAUD:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232AsyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232ASYNCPORTBITS:
                table_entry->old_rs232AsyncPortBits = table_entry->rs232AsyncPortBits;
                table_entry->rs232AsyncPortBits     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232ASYNCPORTSTOPBITS:
                table_entry->old_rs232AsyncPortStopBits = table_entry->rs232AsyncPortStopBits;
                table_entry->rs232AsyncPortStopBits     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232ASYNCPORTPARITY:
                table_entry->old_rs232AsyncPortParity = table_entry->rs232AsyncPortParity;
                table_entry->rs232AsyncPortParity     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232ASYNCPORTAUTOBAUD:
                table_entry->old_rs232AsyncPortAutobaud = table_entry->rs232AsyncPortAutobaud;
                table_entry->rs232AsyncPortAutobaud     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232AsyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232ASYNCPORTBITS:
                table_entry->rs232AsyncPortBits     = table_entry->old_rs232AsyncPortBits;
                table_entry->old_rs232AsyncPortBits = 0;
                break;
            case COLUMN_RS232ASYNCPORTSTOPBITS:
                table_entry->rs232AsyncPortStopBits     = table_entry->old_rs232AsyncPortStopBits;
                table_entry->old_rs232AsyncPortStopBits = 0;
                break;
            case COLUMN_RS232ASYNCPORTPARITY:
                table_entry->rs232AsyncPortParity     = table_entry->old_rs232AsyncPortParity;
                table_entry->old_rs232AsyncPortParity = 0;
                break;
            case COLUMN_RS232ASYNCPORTAUTOBAUD:
                table_entry->rs232AsyncPortAutobaud     = table_entry->old_rs232AsyncPortAutobaud;
                table_entry->old_rs232AsyncPortAutobaud = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
  # Determine the first/last column names

/** Initialize the rs232SyncPortTable table by defining its contents and how it's structured */
void
initialize_table_rs232SyncPortTable(void)
{
    static oid rs232SyncPortTable_oid[] = {1,3,6,1,2,1,10,33,4};
    size_t rs232SyncPortTable_oid_len   = OID_LENGTH(rs232SyncPortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "rs232SyncPortTable",     rs232SyncPortTable_handler,
              rs232SyncPortTable_oid, rs232SyncPortTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: rs232SyncPortIndex */
                           0);
    table_info->min_column = COLUMN_RS232SYNCPORTINDEX;
    table_info->max_column = COLUMN_RS232SYNCPORTMINFLAGS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = rs232SyncPortTable_get_first_data_point;
    iinfo->get_next_data_point  = rs232SyncPortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct rs232SyncPortTable_entry {
    /* Index values */
    long rs232SyncPortIndex;

    /* Column values */
    long rs232SyncPortIndex;
    long rs232SyncPortClockSource;
    long old_rs232SyncPortClockSource;
    u_long rs232SyncPortFrameCheckErrs;
    u_long rs232SyncPortTransmitUnderrunErrs;
    u_long rs232SyncPortReceiveOverrunErrs;
    u_long rs232SyncPortInterruptedFrames;
    u_long rs232SyncPortAbortedFrames;
    long rs232SyncPortRole;
    long old_rs232SyncPortRole;
    long rs232SyncPortEncoding;
    long old_rs232SyncPortEncoding;
    long rs232SyncPortRTSControl;
    long old_rs232SyncPortRTSControl;
    long rs232SyncPortRTSCTSDelay;
    long old_rs232SyncPortRTSCTSDelay;
    long rs232SyncPortMode;
    long old_rs232SyncPortMode;
    long rs232SyncPortIdlePattern;
    long old_rs232SyncPortIdlePattern;
    long rs232SyncPortMinFlags;
    long old_rs232SyncPortMinFlags;

    /* Illustrate using a simple linked list */
    int   valid;
    struct rs232SyncPortTable_entry *next;
};

struct rs232SyncPortTable_entry  *rs232SyncPortTable_head;

/* create a new row in the (unsorted) table */
struct rs232SyncPortTable_entry *
rs232SyncPortTable_createEntry(
                 long  rs232SyncPortIndex,
                ) {
    struct rs232SyncPortTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct rs232SyncPortTable_entry);
    if (!entry)
        return NULL;

    entry->rs232SyncPortIndex = rs232SyncPortIndex;
    entry->next = rs232SyncPortTable_head;
    rs232SyncPortTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
rs232SyncPortTable_removeEntry( struct rs232SyncPortTable_entry *entry ) {
    struct rs232SyncPortTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = rs232SyncPortTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        rs232SyncPortTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
rs232SyncPortTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = rs232SyncPortTable_head;
    return rs232SyncPortTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
rs232SyncPortTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct rs232SyncPortTable_entry *entry = (struct rs232SyncPortTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rs232SyncPortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the rs232SyncPortTable table */
int
rs232SyncPortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct rs232SyncPortTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232SyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232SYNCPORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232SyncPortIndex);
                break;
            case COLUMN_RS232SYNCPORTCLOCKSOURCE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232SyncPortClockSource);
                break;
            case COLUMN_RS232SYNCPORTFRAMECHECKERRS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232SyncPortFrameCheckErrs);
                break;
            case COLUMN_RS232SYNCPORTTRANSMITUNDERRUNERRS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232SyncPortTransmitUnderrunErrs);
                break;
            case COLUMN_RS232SYNCPORTRECEIVEOVERRUNERRS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232SyncPortReceiveOverrunErrs);
                break;
            case COLUMN_RS232SYNCPORTINTERRUPTEDFRAMES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232SyncPortInterruptedFrames);
                break;
            case COLUMN_RS232SYNCPORTABORTEDFRAMES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232SyncPortAbortedFrames);
                break;
            case COLUMN_RS232SYNCPORTROLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232SyncPortRole);
                break;
            case COLUMN_RS232SYNCPORTENCODING:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232SyncPortEncoding);
                break;
            case COLUMN_RS232SYNCPORTRTSCONTROL:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232SyncPortRTSControl);
                break;
            case COLUMN_RS232SYNCPORTRTSCTSDELAY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232SyncPortRTSCTSDelay);
                break;
            case COLUMN_RS232SYNCPORTMODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232SyncPortMode);
                break;
            case COLUMN_RS232SYNCPORTIDLEPATTERN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232SyncPortIdlePattern);
                break;
            case COLUMN_RS232SYNCPORTMINFLAGS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232SyncPortMinFlags);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232SyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232SYNCPORTCLOCKSOURCE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232SYNCPORTROLE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232SYNCPORTENCODING:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232SYNCPORTRTSCONTROL:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232SYNCPORTRTSCTSDELAY:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232SYNCPORTMODE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232SYNCPORTIDLEPATTERN:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232SYNCPORTMINFLAGS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232SyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232SYNCPORTCLOCKSOURCE:
                table_entry->old_rs232SyncPortClockSource = table_entry->rs232SyncPortClockSource;
                table_entry->rs232SyncPortClockSource     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232SYNCPORTROLE:
                table_entry->old_rs232SyncPortRole = table_entry->rs232SyncPortRole;
                table_entry->rs232SyncPortRole     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232SYNCPORTENCODING:
                table_entry->old_rs232SyncPortEncoding = table_entry->rs232SyncPortEncoding;
                table_entry->rs232SyncPortEncoding     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232SYNCPORTRTSCONTROL:
                table_entry->old_rs232SyncPortRTSControl = table_entry->rs232SyncPortRTSControl;
                table_entry->rs232SyncPortRTSControl     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232SYNCPORTRTSCTSDELAY:
                table_entry->old_rs232SyncPortRTSCTSDelay = table_entry->rs232SyncPortRTSCTSDelay;
                table_entry->rs232SyncPortRTSCTSDelay     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232SYNCPORTMODE:
                table_entry->old_rs232SyncPortMode = table_entry->rs232SyncPortMode;
                table_entry->rs232SyncPortMode     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232SYNCPORTIDLEPATTERN:
                table_entry->old_rs232SyncPortIdlePattern = table_entry->rs232SyncPortIdlePattern;
                table_entry->rs232SyncPortIdlePattern     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232SYNCPORTMINFLAGS:
                table_entry->old_rs232SyncPortMinFlags = table_entry->rs232SyncPortMinFlags;
                table_entry->rs232SyncPortMinFlags     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232SyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232SYNCPORTCLOCKSOURCE:
                table_entry->rs232SyncPortClockSource     = table_entry->old_rs232SyncPortClockSource;
                table_entry->old_rs232SyncPortClockSource = 0;
                break;
            case COLUMN_RS232SYNCPORTROLE:
                table_entry->rs232SyncPortRole     = table_entry->old_rs232SyncPortRole;
                table_entry->old_rs232SyncPortRole = 0;
                break;
            case COLUMN_RS232SYNCPORTENCODING:
                table_entry->rs232SyncPortEncoding     = table_entry->old_rs232SyncPortEncoding;
                table_entry->old_rs232SyncPortEncoding = 0;
                break;
            case COLUMN_RS232SYNCPORTRTSCONTROL:
                table_entry->rs232SyncPortRTSControl     = table_entry->old_rs232SyncPortRTSControl;
                table_entry->old_rs232SyncPortRTSControl = 0;
                break;
            case COLUMN_RS232SYNCPORTRTSCTSDELAY:
                table_entry->rs232SyncPortRTSCTSDelay     = table_entry->old_rs232SyncPortRTSCTSDelay;
                table_entry->old_rs232SyncPortRTSCTSDelay = 0;
                break;
            case COLUMN_RS232SYNCPORTMODE:
                table_entry->rs232SyncPortMode     = table_entry->old_rs232SyncPortMode;
                table_entry->old_rs232SyncPortMode = 0;
                break;
            case COLUMN_RS232SYNCPORTIDLEPATTERN:
                table_entry->rs232SyncPortIdlePattern     = table_entry->old_rs232SyncPortIdlePattern;
                table_entry->old_rs232SyncPortIdlePattern = 0;
                break;
            case COLUMN_RS232SYNCPORTMINFLAGS:
                table_entry->rs232SyncPortMinFlags     = table_entry->old_rs232SyncPortMinFlags;
                table_entry->old_rs232SyncPortMinFlags = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
  # Determine the first/last column names

/** Initialize the rs232InSigTable table by defining its contents and how it's structured */
void
initialize_table_rs232InSigTable(void)
{
    static oid rs232InSigTable_oid[] = {1,3,6,1,2,1,10,33,5};
    size_t rs232InSigTable_oid_len   = OID_LENGTH(rs232InSigTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "rs232InSigTable",     rs232InSigTable_handler,
              rs232InSigTable_oid, rs232InSigTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: rs232InSigPortIndex */
                           ASN_INTEGER,  /* index: rs232InSigName */
                           0);
    table_info->min_column = COLUMN_RS232INSIGPORTINDEX;
    table_info->max_column = COLUMN_RS232INSIGCHANGES;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = rs232InSigTable_get_first_data_point;
    iinfo->get_next_data_point  = rs232InSigTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct rs232InSigTable_entry {
    /* Index values */
    long rs232InSigPortIndex;
    long rs232InSigName;

    /* Column values */
    long rs232InSigPortIndex;
    long rs232InSigName;
    long rs232InSigState;
    u_long rs232InSigChanges;

    /* Illustrate using a simple linked list */
    int   valid;
    struct rs232InSigTable_entry *next;
};

struct rs232InSigTable_entry  *rs232InSigTable_head;

/* create a new row in the (unsorted) table */
struct rs232InSigTable_entry *
rs232InSigTable_createEntry(
                 long  rs232InSigPortIndex,
                 long  rs232InSigName,
                ) {
    struct rs232InSigTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct rs232InSigTable_entry);
    if (!entry)
        return NULL;

    entry->rs232InSigPortIndex = rs232InSigPortIndex;
    entry->rs232InSigName = rs232InSigName;
    entry->next = rs232InSigTable_head;
    rs232InSigTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
rs232InSigTable_removeEntry( struct rs232InSigTable_entry *entry ) {
    struct rs232InSigTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = rs232InSigTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        rs232InSigTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
rs232InSigTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = rs232InSigTable_head;
    return rs232InSigTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
rs232InSigTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct rs232InSigTable_entry *entry = (struct rs232InSigTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rs232InSigPortIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rs232InSigName );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the rs232InSigTable table */
int
rs232InSigTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct rs232InSigTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232InSigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232INSIGPORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232InSigPortIndex);
                break;
            case COLUMN_RS232INSIGNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232InSigName);
                break;
            case COLUMN_RS232INSIGSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232InSigState);
                break;
            case COLUMN_RS232INSIGCHANGES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232InSigChanges);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
  # Determine the first/last column names

/** Initialize the rs232OutSigTable table by defining its contents and how it's structured */
void
initialize_table_rs232OutSigTable(void)
{
    static oid rs232OutSigTable_oid[] = {1,3,6,1,2,1,10,33,6};
    size_t rs232OutSigTable_oid_len   = OID_LENGTH(rs232OutSigTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "rs232OutSigTable",     rs232OutSigTable_handler,
              rs232OutSigTable_oid, rs232OutSigTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: rs232OutSigPortIndex */
                           ASN_INTEGER,  /* index: rs232OutSigName */
                           0);
    table_info->min_column = COLUMN_RS232OUTSIGPORTINDEX;
    table_info->max_column = COLUMN_RS232OUTSIGCHANGES;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = rs232OutSigTable_get_first_data_point;
    iinfo->get_next_data_point  = rs232OutSigTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct rs232OutSigTable_entry {
    /* Index values */
    long rs232OutSigPortIndex;
    long rs232OutSigName;

    /* Column values */
    long rs232OutSigPortIndex;
    long rs232OutSigName;
    long rs232OutSigState;
    u_long rs232OutSigChanges;

    /* Illustrate using a simple linked list */
    int   valid;
    struct rs232OutSigTable_entry *next;
};

struct rs232OutSigTable_entry  *rs232OutSigTable_head;

/* create a new row in the (unsorted) table */
struct rs232OutSigTable_entry *
rs232OutSigTable_createEntry(
                 long  rs232OutSigPortIndex,
                 long  rs232OutSigName,
                ) {
    struct rs232OutSigTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct rs232OutSigTable_entry);
    if (!entry)
        return NULL;

    entry->rs232OutSigPortIndex = rs232OutSigPortIndex;
    entry->rs232OutSigName = rs232OutSigName;
    entry->next = rs232OutSigTable_head;
    rs232OutSigTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
rs232OutSigTable_removeEntry( struct rs232OutSigTable_entry *entry ) {
    struct rs232OutSigTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = rs232OutSigTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        rs232OutSigTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
rs232OutSigTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = rs232OutSigTable_head;
    return rs232OutSigTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
rs232OutSigTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct rs232OutSigTable_entry *entry = (struct rs232OutSigTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rs232OutSigPortIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rs232OutSigName );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the rs232OutSigTable table */
int
rs232OutSigTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct rs232OutSigTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232OutSigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232OUTSIGPORTINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232OutSigPortIndex);
                break;
            case COLUMN_RS232OUTSIGNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232OutSigName);
                break;
            case COLUMN_RS232OUTSIGSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232OutSigState);
                break;
            case COLUMN_RS232OUTSIGCHANGES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->rs232OutSigChanges);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
