/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef SERIALTABLE_DATA_ACCESS_H
#define SERIALTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table serialTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * SYSBAS-MIB::serialTable is subid 3 of sysbas.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.1.3, length: 8
*/


    int serialTable_init_data(serialTable_registration * serialTable_reg);


void serialTable_container_init(netsnmp_container **container_ptr_ptr);
void serialTable_container_shutdown(netsnmp_container *container_ptr);

int serialTable_container_load(netsnmp_container *container);
void serialTable_container_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int serialTable_row_prep( serialTable_rowreq_ctx *rowreq_ctx);

int serialTable_validate_index( serialTable_registration * serialTable_reg,
                               serialTable_rowreq_ctx *rowreq_ctx);
int portIndex_check_index( serialTable_rowreq_ctx *rowreq_ctx ); /* internal */


#ifdef __cplusplus
}
#endif

#endif /* SERIALTABLE_DATA_ACCESS_H */
