/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "serialTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "serialTable_interface.h"

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table serialTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * SYSBAS-MIB::serialTable is subid 3 of sysbas.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.1.3, length: 8
*/
typedef struct serialTable_interface_ctx_s {

   netsnmp_container              *container;

   serialTable_registration *      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

    u_int                             table_dirty;

} serialTable_interface_ctx;

static serialTable_interface_ctx serialTable_if_ctx;

static void _serialTable_container_init(
    serialTable_interface_ctx *if_ctx);
static void _serialTable_container_shutdown(
    serialTable_interface_ctx *if_ctx);


netsnmp_container *
serialTable_container_get( void )
{
    return serialTable_if_ctx.container;
}

serialTable_registration *
serialTable_registration_get( void )
{
    return serialTable_if_ctx.user_ctx;
}

serialTable_registration *
serialTable_registration_set( serialTable_registration * newreg )
{
    serialTable_registration * old = serialTable_if_ctx.user_ctx;
    serialTable_if_ctx.user_ctx = newreg;
    return old;
}

int
serialTable_container_size( void )
{
    return CONTAINER_SIZE(serialTable_if_ctx.container);
}

u_int
serialTable_dirty_get( void )
{
    return serialTable_if_ctx.table_dirty;
}

void
serialTable_dirty_set( u_int status )
{
    DEBUGMSGTL(("serialTable:serialTable_dirty_set",
                "called. was %d, now %d\n",
                serialTable_if_ctx.table_dirty, status));
    serialTable_if_ctx.table_dirty = status;
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_serialTable_pre_request;
static Netsnmp_Node_Handler _mfd_serialTable_post_request;
static Netsnmp_Node_Handler _mfd_serialTable_object_lookup;
static Netsnmp_Node_Handler _mfd_serialTable_get_values;
static Netsnmp_Node_Handler _mfd_serialTable_check_objects;
static Netsnmp_Node_Handler _mfd_serialTable_undo_setup;
static Netsnmp_Node_Handler _mfd_serialTable_set_values;
static Netsnmp_Node_Handler _mfd_serialTable_undo_cleanup;
static Netsnmp_Node_Handler _mfd_serialTable_undo_values;
static Netsnmp_Node_Handler _mfd_serialTable_commit;
static Netsnmp_Node_Handler _mfd_serialTable_undo_commit;
static Netsnmp_Node_Handler _mfd_serialTable_irreversible_commit;

NETSNMP_STATIC_INLINE int _serialTable_undo_column( serialTable_rowreq_ctx *rowreq_ctx,
                                                   netsnmp_variable_list *var, int column );

NETSNMP_STATIC_INLINE int _serialTable_check_indexes(serialTable_rowreq_ctx * rowreq_ctx);

serialTable_data *serialTable_allocate_data(void);

/**
 * @internal
 * Initialize the table serialTable 
 *    (Define its contents and how it's structured)
 */
void
_serialTable_initialize_interface(serialTable_registration * reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &serialTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &serialTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:serialTable:_serialTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for serialTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_INTEGER, /** index: portIndex */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrival. */
    tbl_info->min_column = SERIALTABLE_MIN_COL;
    tbl_info->max_column = SERIALTABLE_MAX_COL;

    /*
     * save users context
     */
    serialTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    serialTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _serialTable_container_init(&serialTable_if_ctx);
    if (NULL == serialTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for serialTable\n");
        return;
    }
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_serialTable_object_lookup;
    access_multiplexer->get_values = _mfd_serialTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_serialTable_pre_request;
    access_multiplexer->post_request = _mfd_serialTable_post_request;


    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks = _mfd_serialTable_check_objects;
    access_multiplexer->undo_setup = _mfd_serialTable_undo_setup;
    access_multiplexer->undo_cleanup = _mfd_serialTable_undo_cleanup;
    access_multiplexer->set_values = _mfd_serialTable_set_values;
    access_multiplexer->undo_sets = _mfd_serialTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit = _mfd_serialTable_commit;
    access_multiplexer->undo_commit = _mfd_serialTable_undo_commit;
    access_multiplexer->irreversible_commit = _mfd_serialTable_irreversible_commit;

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("serialTable:init_serialTable",
                "Registering serialTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("serialTable", handler,
                                                  serialTable_oid,
                                                  serialTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
                                                  HANDLER_CAN_RWRITE
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table serialTable\n");
        return;
    }
    reginfo->my_reg_void = &serialTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            serialTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

} /* _serialTable_initialize_interface */

/**
 * @internal
 * Shutdown the table serialTable
 */
void
_serialTable_shutdown_interface(serialTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _serialTable_container_shutdown(&serialTable_if_ctx);
}

void
serialTable_valid_columns_set(netsnmp_column_info *vc)
{
    serialTable_if_ctx.tbl_info.valid_columns = vc;
} /* serialTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
serialTable_index_to_oid(netsnmp_index *oid_idx,
                         serialTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * portIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/r/d/h
     */
    netsnmp_variable_list var_portIndex;

    /*
     * set up varbinds
     */
    memset( &var_portIndex, 0x00, sizeof(var_portIndex) );
    var_portIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_portIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:serialTable:serialTable_index_to_oid","called\n"));

        /* portIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/r/d/h */
    snmp_set_var_value(&var_portIndex, (u_char*)&mib_idx->portIndex,
                       sizeof(mib_idx->portIndex));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_portIndex);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_portIndex );

    return err;
} /* serialTable_index_to_oid */

/**
 * extract serialTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
serialTable_index_from_oid(netsnmp_index *oid_idx,
                         serialTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * portIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/r/d/h
     */
    netsnmp_variable_list var_portIndex;

    /*
     * set up varbinds
     */
    memset( &var_portIndex, 0x00, sizeof(var_portIndex) );
    var_portIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_portIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:serialTable:serialTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_portIndex );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    mib_idx->portIndex = *((long *)var_portIndex.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_portIndex );

    return err;
} /* serialTable_index_from_oid */


/*
 * serialTable_allocate_data
 *
 * Purpose: create new serialTable_data.
 */
serialTable_data *
serialTable_allocate_data(void)
{
    serialTable_data *rtn = SNMP_MALLOC_TYPEDEF(serialTable_data);

    DEBUGMSGTL(("verbose:serialTable:serialTable_allocate_data","called\n"));

    if(NULL == rtn) {
        snmp_log(LOG_ERR, "unable to malloc memory for new "
                 "serialTable_data.\n");
    }

    return rtn;
} /* serialTable_allocate_data */

/*
 * serialTable_release_data
 *
 * Purpose: release serialTable data.
 */
void
serialTable_release_data(serialTable_data *data)
{
    DEBUGMSGTL(("verbose:serialTable:serialTable_release_data","called\n"));

    free(data);
} /* serialTable_release_data */

/* *********************************************************************
 * @internal
 * allocate resources for a serialTable_rowreq_ctx
 */
serialTable_rowreq_ctx *
serialTable_allocate_rowreq_ctx(void *user_init_ctx)
{
    serialTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(serialTable_rowreq_ctx);

    DEBUGMSGTL(("internal:serialTable:serialTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "serialTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->serialTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if (!(rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER)) {
        if(SNMPERR_SUCCESS !=
            serialTable_rowreq_ctx_init(rowreq_ctx, user_init_ctx)) {
           serialTable_release_rowreq_ctx(rowreq_ctx);
           rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
} /* serialTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a serialTable_rowreq_ctx
 */
void
serialTable_release_rowreq_ctx(serialTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:serialTable:serialTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    serialTable_rowreq_ctx_cleanup(rowreq_ctx);

    if(rowreq_ctx->undo)
        serialTable_release_data(rowreq_ctx->undo);
 
    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* serialTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_serialTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc;

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_pre_request",
                "called\n"));
    
    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:serialTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }
        
    rc = serialTable_pre_request(serialTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("serialTable","error %d from "
                    "serialTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_serialTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    int rc, packet_rc;

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_post_request",
                "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        serialTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:serialTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }
    
    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    if ((MFD_SUCCESS != packet_rc) && serialTable_dirty_get()) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        snmp_log(LOG_WARNING, "serialTable dirty flag set in post_request "
                 "but status != SUCCESS.\n");
    }

    rc = serialTable_post_request(serialTable_if_ctx.user_ctx,packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("serialTable","error %d from "
                    "serialTable_post_request\n", rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_post_request */

/**
 * @internal
 * wrapper
 */
static serialTable_rowreq_ctx *
_mfd_serialTable_rowreq_from_index(netsnmp_index *oid_idx, int * rc_ptr)
{
    serialTable_rowreq_ctx * rowreq_ctx;
    serialTable_mib_index mib_idx;
    int rc;

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_rowreq_from_index",
                "called\n"));

    if (NULL == rc_ptr)
        rc_ptr = &rc;
    *rc_ptr = MFD_SUCCESS;

    memset(&mib_idx, 0x0, sizeof(mib_idx));
    
    /*
     * try to parse oid
     */
    *rc_ptr = serialTable_index_from_oid(oid_idx, &mib_idx);
    if(MFD_SUCCESS != *rc_ptr) {
        DEBUGMSGT(("serialTable", "error parsing index\n"));
        return NULL;
    }

    /*
     * allocate new context
     */
    rowreq_ctx = serialTable_allocate_rowreq_ctx(NULL);
    if (NULL == rowreq_ctx) {
        *rc_ptr = MFD_ERROR;
        return NULL; /* msg already logged */
    }
    
    memcpy(&rowreq_ctx->tbl_idx, &mib_idx, sizeof(mib_idx));

    /*
     * check indexes
     */
    *rc_ptr = _serialTable_check_indexes(rowreq_ctx);
    if(MFD_SUCCESS != *rc_ptr) {
        netsnmp_assert((*rc_ptr == SNMP_ERR_NOCREATION) ||
                       (*rc_ptr == SNMP_ERR_INCONSISTENTNAME));
        serialTable_release_rowreq_ctx(rowreq_ctx);
        return NULL;
    }

    /*
     * copy indexes
     */
    rowreq_ctx->oid_idx.len = oid_idx->len;
    memcpy(rowreq_ctx->oid_idx.oids, oid_idx->oids, oid_idx->len * sizeof(oid));

    return rowreq_ctx;
} /* _mfd_serialTable_rowreq_from_index */


/**
 * @internal
 * wrapper
 */
static int
_mfd_serialTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc = SNMP_ERR_NOERROR;
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * serialTable_interface_ctx *if_ctx =
     *             (serialTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        netsnmp_table_request_info *tblreq_info;
        netsnmp_index oid_idx;

        tblreq_info = netsnmp_extract_table_info(requests);
        if(NULL == tblreq_info) {
            snmp_log(LOG_ERR, "request had no table info\n");
            return MFD_ERROR;
        }

        /*
         * try create rowreq
         */
        oid_idx.oids = tblreq_info->index_oid;
        oid_idx.len = tblreq_info->index_oid_len;

        rowreq_ctx = _mfd_serialTable_rowreq_from_index(&oid_idx, &rc);
        if(MFD_SUCCESS == rc) {
            netsnmp_assert(NULL != rowreq_ctx);
            rowreq_ctx->rowreq_flags |= MFD_ROW_CREATED;
            /*
             * add rowreq_ctx to request data lists
             */
            netsnmp_container_table_row_insert(requests, (netsnmp_index*)rowreq_ctx);
        }
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        serialTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
} /* _mfd_serialTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_serialTable_get_column( serialTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_get_column",
                "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* portName(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/h */
    case COLUMN_PORTNAME:
    var->type = ASN_OCTET_STR;
rc = portName_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* socketNumber(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_SOCKETNUMBER:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = socketNumber_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* protocol(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_PROTOCOL:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = protocol_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* deviceType(5)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_DEVICETYPE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = deviceType_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* remoteIPAddress(6)/IPADDR/ASN_IPADDRESS/u_long(u_long)//l/A/w/e/r/d/h */
    case COLUMN_REMOTEIPADDRESS:
    var->val_len = sizeof(u_long);
    var->type = ASN_IPADDRESS;
rc = remoteIPAddress_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* remoteSocketNumber(7)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_REMOTESOCKETNUMBER:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = remoteSocketNumber_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* bypassEnable(8)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_BYPASSENABLE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = bypassEnable_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* loginEnable(9)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_LOGINENABLE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = loginEnable_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* loginUsername(10)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h */
    case COLUMN_LOGINUSERNAME:
    var->type = ASN_OCTET_STR;
rc = loginUsername_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* loginPassword(11)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h */
    case COLUMN_LOGINPASSWORD:
    var->type = ASN_OCTET_STR;
rc = loginPassword_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* connectionCount(12)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h */
    case COLUMN_CONNECTIONCOUNT:
    var->val_len = sizeof(u_long);
    var->type = ASN_COUNTER;
rc = connectionCount_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* connectionStatus(13)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CONNECTIONSTATUS:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = connectionStatus_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* serialRowStatus(14)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_SERIALROWSTATUS:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = serialRowStatus_get(rowreq_ctx, (u_long *)var->val.string );
        break;

     default:
        if (SERIALTABLE_MIN_COL <= column && column <= SERIALTABLE_MAX_COL) {
            DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_get_column",
                "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                "unknown column %d in _serialTable_get_column\n", column);
        }
        break;
    }

    return rc;
} /* _serialTable_get_column */

int
_mfd_serialTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _serialTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_get_values */

NETSNMP_STATIC_INLINE int
_serialTable_check_indexes(serialTable_rowreq_ctx * rowreq_ctx)
{
    int                          rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:serialTable:_serialTable_check_indexes","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);


    /* (INDEX) portIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/r/d/h */
       if (MFD_SUCCESS != rc)
          return rc;
        rc = portIndex_check_index( rowreq_ctx );
       if(MFD_SUCCESS != rc)
           return SNMP_ERR_NOCREATION;

    /*
     * if individual parts look ok, check them as a whole
     */
    return serialTable_validate_index( serialTable_if_ctx.user_ctx, rowreq_ctx );
} /* _serialTable_check_indexes */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
NETSNMP_STATIC_INLINE int
_serialTable_check_column( serialTable_rowreq_ctx *rowreq_ctx,
                         netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:serialTable:_serialTable_check_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {
    /* (INDEX) portIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/r/d/h */
    case COLUMN_PORTINDEX:
        rc = SNMP_ERR_NOTWRITABLE; /* can not change index of active row */
        break;

    /* portName(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/h */
    case COLUMN_PORTNAME:
    rc = netsnmp_check_vb_type_and_max_size( var, ASN_OCTET_STR,
        sizeof( rowreq_ctx->data.portName ) );
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("serialTable:_serialTable_check_column:portName",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = portName_check_value( rowreq_ctx, (char *)var->val.string, var->val_len );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from portName_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* socketNumber(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_SOCKETNUMBER:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* protocol(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_PROTOCOL:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* deviceType(5)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_DEVICETYPE:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* remoteIPAddress(6)/IPADDR/ASN_IPADDRESS/u_long(u_long)//l/A/w/e/r/d/h */
    case COLUMN_REMOTEIPADDRESS:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* remoteSocketNumber(7)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_REMOTESOCKETNUMBER:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* bypassEnable(8)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_BYPASSENABLE:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* loginEnable(9)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_LOGINENABLE:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* loginUsername(10)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h */
    case COLUMN_LOGINUSERNAME:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* loginPassword(11)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h */
    case COLUMN_LOGINPASSWORD:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* connectionCount(12)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h */
    case COLUMN_CONNECTIONCOUNT:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* connectionStatus(13)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_CONNECTIONSTATUS:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* serialRowStatus(14)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_SERIALROWSTATUS:
rc = netsnmp_check_vb_rowstatus_value(var);
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("serialTable:_serialTable_check_column:serialRowStatus",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = serialRowStatus_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from serialRowStatus_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column %d in _serialTable_check_column\n", column);
    }

    return rc;
} /* _serialTable_check_column */

int
_mfd_serialTable_check_objects(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc;

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_check_objects","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {

        /*
         * get column number from table request info, and check that column
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;

        rc = _serialTable_check_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));
            break;
        }

    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_check_objects */


/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_serialTable_undo_setup_column( serialTable_rowreq_ctx *rowreq_ctx, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:serialTable:_serialTable_undo_setup_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* portName(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/h */
    case COLUMN_PORTNAME:
        rowreq_ctx->column_set_flags |= COLUMN_PORTNAME_FLAG;
        rc = portName_undo_setup(rowreq_ctx );
        break;

    /* serialRowStatus(14)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_SERIALROWSTATUS:
        rowreq_ctx->column_set_flags |= COLUMN_SERIALROWSTATUS_FLAG;
        rc = serialRowStatus_undo_setup(rowreq_ctx );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _serialTable_undo_setup_column\n", column);
         break;
    }

    return rc;
} /* _serialTable_undo_setup_column */


/**
 * @internal
 * undo setup
 */
int
_mfd_serialTable_undo_setup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_undo_setup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = serialTable_allocate_data();
    if(NULL == rowreq_ctx->undo) {
        /** msg already logged */
        netsnmp_request_set_error_all(requests, SNMP_ERR_RESOURCEUNAVAILABLE);
        return SNMP_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = serialTable_undo_setup(rowreq_ctx);
    if (MFD_SUCCESS != rc)  {
        DEBUGMSGTL(("serialTable:mfd","error %d from "
                    "serialTable_undo_setup\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    else {
        /*
         * column undo setup
         */
        netsnmp_table_request_info * tri;
        for(;requests; requests = requests->next) {
            /*
             * set column data
             */
            tri = netsnmp_extract_table_info(requests);
            if(NULL == tri)
                continue;
            
            rc = _serialTable_undo_setup_column(rowreq_ctx, tri->colnum);
            if(MFD_SUCCESS != rc)  {
                DEBUGMSGTL(("serialTable:mfd","error %d from "
                            "serialTable_undo_setup_column\n", rc));
                netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
            }
        } /* for results */
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int
_mfd_serialTable_undo_cleanup(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    int rc;

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_undo_cleanup","called\n"));

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if (NULL == rowreq_ctx)
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = serialTable_undo_cleanup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("serialTable:mfd","error %d from "
                    "serialTable_undo_cleanup\n", rc));
    }

    /*
     * release undo context, if needed
     */
    if(rowreq_ctx->undo) {
         serialTable_release_data(rowreq_ctx->undo);
         rowreq_ctx->undo = NULL;
    }


    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_undo_cleanup */

/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_serialTable_set_column( serialTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:serialTable:_serialTable_set_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* portName(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/h */
    case COLUMN_PORTNAME:
        rowreq_ctx->column_set_flags |= COLUMN_PORTNAME_FLAG;
        rc = portName_set(rowreq_ctx, (char *)var->val.string, var->val_len );
        break;

    /* serialRowStatus(14)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_SERIALROWSTATUS:
        rowreq_ctx->column_set_flags |= COLUMN_SERIALROWSTATUS_FLAG;
        rc = serialRowStatus_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _serialTable_set_column\n", column);
         rc = SNMP_ERR_GENERR;
         break;
    }
    
    return rc;
} /* _serialTable_set_column */

int
_mfd_serialTable_set_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc = SNMP_ERR_NOERROR;

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_set_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rowreq_ctx->column_set_flags = 0;
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _serialTable_set_column(rowreq_ctx,
                                    requests->requestvb, tri->colnum);
        if(MFD_SUCCESS != rc)  {
            DEBUGMSGTL(("serialTable:mfd","error %d from "
                        "serialTable_set_column\n", rc));
            netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int
_mfd_serialTable_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = serialTable_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("serialTable:mfd","error %d from "
                    "serialTable_commit\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        /*
         * if we successfully commited this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        serialTable_dirty_set( serialTable_dirty_get() + 1 ); /* set table dirty flag */
    }

    return SNMP_ERR_NOERROR;
}

int
_mfd_serialTable_undo_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_undo_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        u_int  d = serialTable_dirty_get();

        netsnmp_assert(d != 0);
        if(d)
            serialTable_dirty_set( d - 1 );
    }

    rc = serialTable_undo_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("serialTable:mfd","error %d from "
                    "serialTable_undo_commit\n", rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        snmp_log(LOG_WARNING, "serialTable row dirty flag still set after undo_commit\n");
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * undo the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_serialTable_undo_column( serialTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:serialTable:_serialTable_undo_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* portName(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/W/e/r/d/h */
    case COLUMN_PORTNAME:
        rc = portName_undo(rowreq_ctx);
        break;

    /* serialRowStatus(14)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_SERIALROWSTATUS:
        rc = serialRowStatus_undo(rowreq_ctx);
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _serialTable_undo_column\n", column);
         break;
    }

    return rc;
} /* _serialTable_undo_column */

int
_mfd_serialTable_undo_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;

    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_undo_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = serialTable_undo(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("serialTable:mfd","error %d from "
                    "serialTable_undo\n", rc));
    }
    
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _serialTable_undo_column(rowreq_ctx, requests->requestvb,
                                     tri->colnum);
        if (MFD_SUCCESS != rc) {
            /*
             * nothing we can do about it but log it
             */
            DEBUGMSGTL(("serialTable:mfd","error %d from "
                        "serialTable_undo_column\n", rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int
_mfd_serialTable_irreversible_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    serialTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:serialTable:_mfd_serialTable_irreversible:commit","called\n"));
   
    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED) {
        if (! (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED))
            CONTAINER_REMOVE(serialTable_if_ctx.container, rowreq_ctx);
    }
    else {
        if (rowreq_ctx->column_set_flags) {
           rowreq_ctx->column_set_flags = 0;
        }
        if (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED) {
            rowreq_ctx->rowreq_flags &= ~MFD_ROW_CREATED;
            CONTAINER_INSERT(serialTable_if_ctx.container, rowreq_ctx);
        }
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_serialTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
/**
 * @internal
 */
static void
_container_item_free(serialTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:serialTable:_container_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    serialTable_release_rowreq_ctx(rowreq_ctx);
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("internal:serialTable:_container_free","called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "invalid container in serialTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    serialTable_container_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_container_item_free,
                    NULL);
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_serialTable_container_init(serialTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:serialTable:_serialTable_container_init","called\n"));

    /*
     * container init
     */    
    serialTable_container_init(&if_ctx->container);
    if(NULL == if_ctx->container)
        if_ctx->container = netsnmp_container_find("serialTable:table_container");
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "serialTable_container_init\n");
        return;
    }

} /* _serialTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_serialTable_container_shutdown(serialTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:serialTable:_serialTable_container_shutdown","called\n"));

    serialTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

} /* _serialTable_container_shutdown */


serialTable_rowreq_ctx *
serialTable_row_find_by_mib_index(serialTable_mib_index *mib_idx)
{
    serialTable_rowreq_ctx   *rowreq_ctx;
    oid                      oid_tmp[MAX_OID_LEN];
    netsnmp_index            oid_idx;
    int                      rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp)/sizeof(oid);

    /*
     * convert
     */
    rc = serialTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx = CONTAINER_FIND(serialTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}

