/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef SERIALTABLE_INTERFACE_H
#define SERIALTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "serialTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _serialTable_initialize_interface(serialTable_registration * user_ctx,
                                    u_long flags);
void _serialTable_shutdown_interface(serialTable_registration * user_ctx);

serialTable_registration *
serialTable_registration_get( void );

serialTable_registration *
serialTable_registration_set( serialTable_registration * newreg );

netsnmp_container *serialTable_container_get( void );
int serialTable_container_size( void );

u_int serialTable_dirty_get( void );
void serialTable_dirty_set( u_int status );

    serialTable_rowreq_ctx * serialTable_allocate_rowreq_ctx(void *);
void serialTable_release_rowreq_ctx(serialTable_rowreq_ctx *rowreq_ctx);

int serialTable_index_to_oid(netsnmp_index *oid_idx,
                            serialTable_mib_index *mib_idx);
int serialTable_index_from_oid(netsnmp_index *oid_idx,
                              serialTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void serialTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* SERIALTABLE_INTERFACE_H */
/** @} */
