/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "serialTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement serialTable get routines.
 * TODO:240:M: Implement serialTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table serialTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * SYSBAS-MIB::serialTable is subid 3 of sysbas.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.1.3, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement serialTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param portIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
serialTable_indexes_set_tbl_idx(serialTable_mib_index *tbl_idx, long portIndex_val)
{
    DEBUGMSGTL(("verbose:serialTable:serialTable_indexes_set_tbl_idx","called\n"));

    /* portIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/a/w/e/r/d/h */
    tbl_idx->portIndex = portIndex_val;
    

    return MFD_SUCCESS;
} /* serialTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
serialTable_indexes_set(serialTable_rowreq_ctx *rowreq_ctx, long portIndex_val)
{
    DEBUGMSGTL(("verbose:serialTable:serialTable_indexes_set","called\n"));

    if(MFD_SUCCESS != serialTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , portIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != serialTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* serialTable_indexes_set */


/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.portName
 * portName is subid 2 of serialEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1.3.1.2
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the portName data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param portName_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param portName_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by portName.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*portName_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update portName_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
portName_get( serialTable_rowreq_ctx *rowreq_ctx, char **portName_val_ptr_ptr, size_t *portName_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != portName_val_ptr_ptr) && (NULL != *portName_val_ptr_ptr));
   netsnmp_assert( NULL != portName_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:serialTable:portName_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the portName data.
 * copy (* portName_val_ptr_ptr ) data and (* portName_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for portName data
     */
    if ((NULL == (* portName_val_ptr_ptr )) ||
        ((* portName_val_ptr_len_ptr ) <
         (rowreq_ctx->data.portName_len* sizeof(rowreq_ctx->data.portName[0])))) {
        /*
         * allocate space for portName data
         */
        (* portName_val_ptr_ptr ) = malloc(rowreq_ctx->data.portName_len* sizeof(rowreq_ctx->data.portName[0]));
        if(NULL == (* portName_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* portName_val_ptr_len_ptr ) = rowreq_ctx->data.portName_len* sizeof(rowreq_ctx->data.portName[0]);
    memcpy( (* portName_val_ptr_ptr ), rowreq_ctx->data.portName, rowreq_ctx->data.portName_len* sizeof(rowreq_ctx->data.portName[0]) );

    return MFD_SUCCESS;
} /* portName_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.socketNumber
 * socketNumber is subid 3 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.3
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the socketNumber data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param socketNumber_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
socketNumber_get( serialTable_rowreq_ctx *rowreq_ctx, long * socketNumber_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != socketNumber_val_ptr );


    DEBUGMSGTL(("verbose:serialTable:socketNumber_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the socketNumber data.
 * copy (* socketNumber_val_ptr ) from rowreq_ctx->data
 */
    (* socketNumber_val_ptr ) = rowreq_ctx->data.socketNumber;

    return MFD_SUCCESS;
} /* socketNumber_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.protocol
 * protocol is subid 4 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.4
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 7/8. Values:  disabled(0), comRedirect(1), tcpServer(2), tcpClient(3), tcpBroadcast(4), tcpMultiplex(5), udpServer(6), udpClient(7)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the protocol data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param protocol_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
protocol_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * protocol_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != protocol_val_ptr );


    DEBUGMSGTL(("verbose:serialTable:protocol_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the protocol data.
 * copy (* protocol_val_ptr ) from rowreq_ctx->data
 */
    (* protocol_val_ptr ) = rowreq_ctx->data.protocol;

    return MFD_SUCCESS;
} /* protocol_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.deviceType
 * deviceType is subid 5 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.5
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  data(1), modem(2)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the deviceType data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param deviceType_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
deviceType_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * deviceType_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != deviceType_val_ptr );


    DEBUGMSGTL(("verbose:serialTable:deviceType_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the deviceType data.
 * copy (* deviceType_val_ptr ) from rowreq_ctx->data
 */
    (* deviceType_val_ptr ) = rowreq_ctx->data.deviceType;

    return MFD_SUCCESS;
} /* deviceType_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.remoteIPAddress
 * remoteIPAddress is subid 6 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.6
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the remoteIPAddress data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param remoteIPAddress_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
remoteIPAddress_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * remoteIPAddress_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != remoteIPAddress_val_ptr );


    DEBUGMSGTL(("verbose:serialTable:remoteIPAddress_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the remoteIPAddress data.
 * copy (* remoteIPAddress_val_ptr ) from rowreq_ctx->data
 */
    (* remoteIPAddress_val_ptr ) = rowreq_ctx->data.remoteIPAddress;

    return MFD_SUCCESS;
} /* remoteIPAddress_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.remoteSocketNumber
 * remoteSocketNumber is subid 7 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.7
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the remoteSocketNumber data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param remoteSocketNumber_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
remoteSocketNumber_get( serialTable_rowreq_ctx *rowreq_ctx, long * remoteSocketNumber_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != remoteSocketNumber_val_ptr );


    DEBUGMSGTL(("verbose:serialTable:remoteSocketNumber_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the remoteSocketNumber data.
 * copy (* remoteSocketNumber_val_ptr ) from rowreq_ctx->data
 */
    (* remoteSocketNumber_val_ptr ) = rowreq_ctx->data.remoteSocketNumber;

    return MFD_SUCCESS;
} /* remoteSocketNumber_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.bypassEnable
 * bypassEnable is subid 8 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.8
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the bypassEnable data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param bypassEnable_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
bypassEnable_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * bypassEnable_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != bypassEnable_val_ptr );


    DEBUGMSGTL(("verbose:serialTable:bypassEnable_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the bypassEnable data.
 * copy (* bypassEnable_val_ptr ) from rowreq_ctx->data
 */
    (* bypassEnable_val_ptr ) = rowreq_ctx->data.bypassEnable;

    return MFD_SUCCESS;
} /* bypassEnable_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.loginEnable
 * loginEnable is subid 9 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.9
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the loginEnable data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param loginEnable_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
loginEnable_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * loginEnable_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != loginEnable_val_ptr );


    DEBUGMSGTL(("verbose:serialTable:loginEnable_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the loginEnable data.
 * copy (* loginEnable_val_ptr ) from rowreq_ctx->data
 */
    (* loginEnable_val_ptr ) = rowreq_ctx->data.loginEnable;

    return MFD_SUCCESS;
} /* loginEnable_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.loginUsername
 * loginUsername is subid 10 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.10
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the loginUsername data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param loginUsername_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param loginUsername_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by loginUsername.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*loginUsername_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update loginUsername_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
loginUsername_get( serialTable_rowreq_ctx *rowreq_ctx, char **loginUsername_val_ptr_ptr, size_t *loginUsername_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != loginUsername_val_ptr_ptr) && (NULL != *loginUsername_val_ptr_ptr));
   netsnmp_assert( NULL != loginUsername_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:serialTable:loginUsername_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the loginUsername data.
 * copy (* loginUsername_val_ptr_ptr ) data and (* loginUsername_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for loginUsername data
     */
    if ((NULL == (* loginUsername_val_ptr_ptr )) ||
        ((* loginUsername_val_ptr_len_ptr ) <
         (rowreq_ctx->data.loginUsername_len* sizeof(rowreq_ctx->data.loginUsername[0])))) {
        /*
         * allocate space for loginUsername data
         */
        (* loginUsername_val_ptr_ptr ) = malloc(rowreq_ctx->data.loginUsername_len* sizeof(rowreq_ctx->data.loginUsername[0]));
        if(NULL == (* loginUsername_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* loginUsername_val_ptr_len_ptr ) = rowreq_ctx->data.loginUsername_len* sizeof(rowreq_ctx->data.loginUsername[0]);
    memcpy( (* loginUsername_val_ptr_ptr ), rowreq_ctx->data.loginUsername, rowreq_ctx->data.loginUsername_len* sizeof(rowreq_ctx->data.loginUsername[0]) );

    return MFD_SUCCESS;
} /* loginUsername_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.loginPassword
 * loginPassword is subid 11 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.11
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the loginPassword data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param loginPassword_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param loginPassword_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by loginPassword.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*loginPassword_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update loginPassword_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
loginPassword_get( serialTable_rowreq_ctx *rowreq_ctx, char **loginPassword_val_ptr_ptr, size_t *loginPassword_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != loginPassword_val_ptr_ptr) && (NULL != *loginPassword_val_ptr_ptr));
   netsnmp_assert( NULL != loginPassword_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:serialTable:loginPassword_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the loginPassword data.
 * copy (* loginPassword_val_ptr_ptr ) data and (* loginPassword_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for loginPassword data
     */
    if ((NULL == (* loginPassword_val_ptr_ptr )) ||
        ((* loginPassword_val_ptr_len_ptr ) <
         (rowreq_ctx->data.loginPassword_len* sizeof(rowreq_ctx->data.loginPassword[0])))) {
        /*
         * allocate space for loginPassword data
         */
        (* loginPassword_val_ptr_ptr ) = malloc(rowreq_ctx->data.loginPassword_len* sizeof(rowreq_ctx->data.loginPassword[0]));
        if(NULL == (* loginPassword_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* loginPassword_val_ptr_len_ptr ) = rowreq_ctx->data.loginPassword_len* sizeof(rowreq_ctx->data.loginPassword[0]);
    memcpy( (* loginPassword_val_ptr_ptr ), rowreq_ctx->data.loginPassword, rowreq_ctx->data.loginPassword_len* sizeof(rowreq_ctx->data.loginPassword[0]) );

    return MFD_SUCCESS;
} /* loginPassword_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.connectionCount
 * connectionCount is subid 12 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.12
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the connectionCount data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param connectionCount_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
connectionCount_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * connectionCount_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != connectionCount_val_ptr );


    DEBUGMSGTL(("verbose:serialTable:connectionCount_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the connectionCount data.
 * copy (* connectionCount_val_ptr ) from rowreq_ctx->data
 */
    (* connectionCount_val_ptr ) = rowreq_ctx->data.connectionCount;

    return MFD_SUCCESS;
} /* connectionCount_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.connectionStatus
 * connectionStatus is subid 13 of serialEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1.3.1.13
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  idle(1), connected(2)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the connectionStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param connectionStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
connectionStatus_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * connectionStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != connectionStatus_val_ptr );


    DEBUGMSGTL(("verbose:serialTable:connectionStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the connectionStatus data.
 * copy (* connectionStatus_val_ptr ) from rowreq_ctx->data
 */
    (* connectionStatus_val_ptr ) = rowreq_ctx->data.connectionStatus;

    return MFD_SUCCESS;
} /* connectionStatus_get */

/*---------------------------------------------------------------------
 * SYSBAS-MIB::serialEntry.serialRowStatus
 * serialRowStatus is subid 14 of serialEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.1.3.1.14
 * Description:
Column Description
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  active(1), notInService(2), notReady(3), createAndGo(4), createAndWait(5), destroy(6)
 *
 * Its syntax is RowStatus (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the serialRowStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param serialRowStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
serialRowStatus_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * serialRowStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != serialRowStatus_val_ptr );

    (* serialRowStatus_val_ptr ) = rowreq_ctx->data.serialRowStatus;

    return MFD_SUCCESS;
} /* serialRowStatus_get */



/** @} */
