/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file serialTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef SERIALTABLE_DATA_GET_H
#define SERIALTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table serialTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * SYSBAS-MIB::serialTable is subid 3 of sysbas.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.1.3, length: 8
*/
    /*
     * indexes
     */

    int portName_get( serialTable_rowreq_ctx *rowreq_ctx, char **portName_val_ptr_ptr, size_t *portName_val_ptr_len_ptr );
    int socketNumber_get( serialTable_rowreq_ctx *rowreq_ctx, long * socketNumber_val_ptr );
    int protocol_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * protocol_val_ptr );
    int deviceType_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * deviceType_val_ptr );
    int remoteIPAddress_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * remoteIPAddress_val_ptr );
    int remoteSocketNumber_get( serialTable_rowreq_ctx *rowreq_ctx, long * remoteSocketNumber_val_ptr );
    int bypassEnable_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * bypassEnable_val_ptr );
    int loginEnable_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * loginEnable_val_ptr );
    int loginUsername_get( serialTable_rowreq_ctx *rowreq_ctx, char **loginUsername_val_ptr_ptr, size_t *loginUsername_val_ptr_len_ptr );
    int loginPassword_get( serialTable_rowreq_ctx *rowreq_ctx, char **loginPassword_val_ptr_ptr, size_t *loginPassword_val_ptr_len_ptr );
    int connectionCount_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * connectionCount_val_ptr );
    int connectionStatus_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * connectionStatus_val_ptr );
    int serialRowStatus_get( serialTable_rowreq_ctx *rowreq_ctx, u_long * serialRowStatus_val_ptr );


int serialTable_indexes_set_tbl_idx(serialTable_mib_index *tbl_idx, long portIndex_val);
int serialTable_indexes_set(serialTable_rowreq_ctx *rowreq_ctx, long portIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* SERIALTABLE_DATA_GET_H */
/** @} */
