/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for serialTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "serialTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "serialTable_interface.h"

oid serialTable_oid[] = { SERIALTABLE_OID };
int serialTable_oid_size = OID_LENGTH(serialTable_oid);

    serialTable_registration  serialTable_user_context;

void initialize_table_serialTable(void);
void shutdown_table_serialTable(void);


/**
 * Initializes the serialTable module
 */
void
init_serialTable(void)
{
    DEBUGMSGTL(("verbose:serialTable:init_serialTable","called\n"));

    /*
     * TODO:300:o: Perform serialTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("serialTable"))
        initialize_table_serialTable();

} /* init_serialTable */

/**
 * Shut-down the serialTable module (agent is exiting)
 */
void
shutdown_serialTable(void)
{
    if (should_init("serialTable"))
        shutdown_table_serialTable();

}

/**
 * Initialize the table serialTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_serialTable(void)
{
    serialTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:serialTable:initialize_table_serialTable","called\n"));

    /*
     * TODO:301:o: Perform serialTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize serialTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("serialTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _serialTable_initialize_interface(user_context, flags);
} /* initialize_table_serialTable */

/**
 * Shutdown the table serialTable 
 */
void
shutdown_table_serialTable(void)
{
    /*
     * call interface shutdown code
     */
    _serialTable_shutdown_interface(&serialTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
serialTable_rowreq_ctx_init(serialTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:serialTable:serialTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra serialTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* serialTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void serialTable_rowreq_ctx_cleanup(serialTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:serialTable:serialTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra serialTable rowreq cleanup.
     */
} /* serialTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
serialTable_pre_request(serialTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:serialTable:serialTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform serialTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* serialTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
serialTable_post_request(serialTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:serialTable:serialTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform serialTable post-request actions.
     */

    /*
     * check to set if any rows were changed.
     */
    if (serialTable_dirty_get()) {
        /*
         * check if request was successful. If so, this would be
         * a good place to save data to its persistent store.
         */
        if (MFD_SUCCESS == rc) {
            /*
             * save changed rows, if you haven't already
             */
        }
        
        serialTable_dirty_set(0); /* clear table dirty flag */
    }

    return MFD_SUCCESS;
} /* serialTable_post_request */


/** @{ */
