/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef SYSBAS_H
#define SYSBAS_H

/* function declarations */
void init_sysbas(void);
void initialize_table_systemTable(void);
Netsnmp_Node_Handler systemTable_handler;
Netsnmp_First_Data_Point  systemTable_get_first_data_point;
Netsnmp_Next_Data_Point   systemTable_get_next_data_point;
void initialize_table_serialTable(void);
Netsnmp_Node_Handler serialTable_handler;
Netsnmp_First_Data_Point  serialTable_get_first_data_point;
Netsnmp_Next_Data_Point   serialTable_get_next_data_point;
void initialize_table_gpioTable(void);
Netsnmp_Node_Handler gpioTable_handler;
Netsnmp_First_Data_Point  gpioTable_get_first_data_point;
Netsnmp_Next_Data_Point   gpioTable_get_next_data_point;

/* column number definitions for table systemTable */
       #define COLUMN_MACADDRESS		1
       #define COLUMN_IPADDRESS		2
       #define COLUMN_SUBNETMASK		3
       #define COLUMN_GATEWAYADDRESS		4
       #define COLUMN_DNSSERVERADDRESS		5
       #define COLUMN_DDNSSERVERADDRESS		6
       #define COLUMN_NTPSERVERADDRESS		7
       #define COLUMN_PORTVIEWADDRESS		8
       #define COLUMN_LINETYPE		9
       #define COLUMN_NETWORKSPEED		10
       #define COLUMN_DEVICENAME		11
       #define COLUMN_USERNAME		12
       #define COLUMN_PASSWORD		13
       #define COLUMN_PORTVIEWPORTNUMBER		14
       #define COLUMN_SNMPAGENTENABLE		15
       #define COLUMN_TELNETSERVERENABLE		16
       #define COLUMN_FTPSERVERENABLE		17
       #define COLUMN_WEBSERVERENABLE		18
       #define COLUMN_SSHSERVERENABLE		19
       #define COLUMN_TARGETAGENTENABLE		20
       #define COLUMN_MODELNAME		21
       #define COLUMN_DDNSUSERNAME		22
       #define COLUMN_DDNSPASSWORD		23
       #define COLUMN_WEBSITE		24
       #define COLUMN_CONTACT		25
       #define COLUMN_TRAPIPADDRESS		26
       #define COLUMN_TRAPPORTNUMBER		27
       #define COLUMN_TRAPOPTION		28
       #define COLUMN_BOOTLOADERVERSION		29
       #define COLUMN_KERNELVERSION		30
       #define COLUMN_FILESYSTEMVERSION		31
       #define COLUMN_DEVICEINDEXNUMBER		32
       #define COLUMN_INDEX		33
       #define COLUMN_SYSTEMROWSTATUS		34

/* column number definitions for table serialTable */
       #define COLUMN_PORTINDEX		1
       #define COLUMN_PORTNAME		2
       #define COLUMN_SOCKETNUMBER		3
       #define COLUMN_PROTOCOL		4
       #define COLUMN_DEVICETYPE		5
       #define COLUMN_REMOTEIPADDRESS		6
       #define COLUMN_REMOTESOCKETNUMBER		7
       #define COLUMN_BYPASSENABLE		8
       #define COLUMN_LOGINENABLE		9
       #define COLUMN_LOGINUSERNAME		10
       #define COLUMN_LOGINPASSWORD		11
       #define COLUMN_CONNECTIONCOUNT		12
       #define COLUMN_CONNECTIONSTATUS		13
       #define COLUMN_SERIALROWSTATUS		14

/* column number definitions for table gpioTable */
       #define COLUMN_GPIOINDEXNUMBER		1
       #define COLUMN_GPIOSOCKETNUMBER		2
       #define COLUMN_GPIOMODE		3
       #define COLUMN_GPIOVALUE		4
       #define COLUMN_GPIOROWSTATUS		5
#endif /* SYSBAS_H */
